import { useState } from 'react'
import { addDays,addMonths,endOfMonth,format,getDay,parseISO,startOfMonth } from 'date-fns'
import { es } from 'date-fns/locale'
import { ChevronLeft,ChevronRight, X } from 'lucide-react'
import type { Assignment,Consultation,ShiftRequest,Staff } from '../types'
import type { CoverageIssue } from '../lib/coverage'
export default function AbsenceCalendar({initialMonth,staff,requests,assignments,consultations,issues,isSupervisor,onClose,onAssign,onRequest}:{initialMonth:string;staff:Staff[];requests:ShiftRequest[];assignments:Assignment[];consultations:Consultation[];issues:CoverageIssue[];isSupervisor:boolean;onClose:()=>void;onAssign:(date:string,personId?:string)=>void;onRequest:(id:string)=>void}){
 const [month,setMonth]=useState(parseISO(initialMonth+'-01'));const [day,setDay]=useState<string|null>(null)
 const approved=requests.filter(r=>r.status==='approved'&&['vacation','permission'].includes(r.request_type));const days=[];for(let d=startOfMonth(month);d<=endOfMonth(month);d=addDays(d,1))days.push(format(d,'yyyy-MM-dd'))
 const first=(getDay(startOfMonth(month))+6)%7;const key=format(month,'yyyy-MM');const onDay=(date:string)=>approved.filter(r=>r.date_from<=date&&r.date_to>=date);const selected=day?onDay(day):[]
 return <section className="panel absence-calendar"><div className="section-heading"><div><h2>{isSupervisor?'Calendario de ausencias':'Mis ausencias aprobadas'}</h2><p>Vacaciones y permisos aprobados. Se consideran días completos con los datos actuales.</p></div><button className="soft-button" onClick={onClose}><X size={16}/> Volver al cuadrante</button></div><div className="month-switch"><button aria-label="Ausencias: mes anterior" disabled={key<='2026-10'} onClick={()=>{setMonth(addMonths(month,-1));setDay(null)}}><ChevronLeft/></button><strong>{format(month,'MMMM yyyy',{locale:es})}</strong><button aria-label="Ausencias: mes siguiente" disabled={key>='2026-12'} onClick={()=>{setMonth(addMonths(month,1));setDay(null)}}><ChevronRight/></button></div><div className="absence-grid">{['L','M','X','J','V','S','D'].map((d,i)=><strong className="absence-weekday" key={i}>{d}</strong>)}{Array.from({length:first},(_,i)=><div key={`blank${i}`}/>)}{days.map(date=><button className={`absence-day ${day===date?'selected':''}`} key={date} onClick={()=>setDay(date)}><strong>{Number(date.slice(-2))}</strong>{onDay(date).map(r=><span className={r.request_type} key={r.id}>{staff.find(s=>s.id===r.professional_id)?.display_name??'Profesional'}<small>{r.request_type==='vacation'?'Vacaciones':'Permiso'}</small></span>)}</button>)}</div>{day&&<div className="absence-detail"><h3>{format(parseISO(day),"EEEE d 'de' MMMM",{locale:es})}</h3>{!selected.length&&<p>No hay ausencias aprobadas este día.</p>}{selected.map(r=>{const affected=assignments.filter(a=>a.professional_id===r.professional_id&&a.work_date===day);return <article key={r.id}><strong>{staff.find(s=>s.id===r.professional_id)?.display_name} · {r.request_type==='vacation'?'Vacaciones':'Permiso'}</strong><p>{r.date_from} — {r.date_to}</p>{affected.length>0&&<p className="review-text">Turnos que requieren revisión: {affected.map(a=>consultations.find(c=>c.id===a.consultation_id)?.label??a.consultation_id).join(', ')}.</p>}<div className="inline-actions"><button className="soft-button" onClick={()=>onRequest(r.id)}>Ver solicitud</button>{isSupervisor&&affected.length>0&&<button className="soft-button" onClick={()=>onAssign(day,r.professional_id)}>Reorganizar turnos</button>}</div></article>})}{isSupervisor&&issues.some(i=>i.date===day)&&<button className="soft-button" onClick={()=>onAssign(day)}>Revisar cobertura del día ({issues.filter(i=>i.date===day).length})</button>}</div>}</section>
}
