import { useEffect, useMemo, useRef, useState } from 'react'
import { addDays,addMonths,endOfMonth,format,getDay,isSameDay,parseISO,startOfMonth } from 'date-fns'
import { es } from 'date-fns/locale'
import { AlertTriangle,ChevronLeft,ChevronRight,Plus,Copy,Download,CalendarOff } from 'lucide-react'
import { HOLIDAYS,MASCOTS } from '../data/constants'
import type { Assignment,Consultation,CoverageProfile,ShiftRequest,Staff } from '../types'
import type { CoverageIssue } from '../lib/coverage'
import CopySchedule from './CopySchedule'
import AbsenceCalendar from './AbsenceCalendar'
import type { CopyPreviewRow } from '../lib/planning'
import type { ShiftSelection } from './ShiftEditor'
export default function CalendarPanel({staff,assignments,consultations,profile,isSupervisor,issues,focusDate,onSelect,requests,coverageProfiles,syncedAt,onCopy,onRequest}:{staff:Staff[];assignments:Assignment[];consultations:Consultation[];profile:Staff;isSupervisor:boolean;issues:CoverageIssue[];focusDate:string|null;onSelect:(s:ShiftSelection)=>void;requests:ShiftRequest[];coverageProfiles:CoverageProfile[];syncedAt:Date;onCopy:(rows:CopyPreviewRow[],reviewed:boolean)=>Promise<string|null>;onRequest:(id:string)=>void}) {
 const [showCopy,setShowCopy]=useState(false);const [showAbsences,setShowAbsences]=useState(false);const [pdfBusy,setPdfBusy]=useState(false);const [pdfMessage,setPdfMessage]=useState('')
 const [month,setMonth]=useState(parseISO(focusDate??'2026-10-01'));const [filter,setFilter]=useState('all');const [showIssues,setShowIssues]=useState(false)
 const focusedDay=useRef<HTMLButtonElement>(null)
 useEffect(()=>{if(focusDate){setMonth(startOfMonth(parseISO(focusDate)));window.setTimeout(()=>focusedDay.current?.scrollIntoView({block:'nearest',inline:'center',behavior:'smooth'}),100)}},[focusDate])
 const days=useMemo(()=>{const out=[];for(let d=startOfMonth(month);d<=endOfMonth(month);d=addDays(d,1))out.push(d);return out},[month])
 const key=format(month,'yyyy-MM');const monthIssues=issues.filter(i=>i.date.startsWith(key))
 const exportPdf=async()=>{setPdfBusy(true);setPdfMessage('');try { const {downloadRotaPdf}=await import('../lib/rotaPdf');downloadRotaPdf(key,staff.filter(s=>filter==='all'||s.id===filter),assignments,consultations,syncedAt) } catch {setPdfMessage('No se ha podido preparar el PDF. Vuelve a intentarlo.')}finally{setPdfBusy(false)}}
 if(showAbsences)return <AbsenceCalendar initialMonth={key} staff={staff} requests={requests} assignments={assignments} consultations={consultations} issues={issues} isSupervisor={isSupervisor} onClose={()=>setShowAbsences(false)} onAssign={(date,personId)=>onSelect({date,personId})} onRequest={onRequest}/>
 return <section className="content-section"><div className="section-heading"><div><span className="eyebrow">Todo el mes de un vistazo</span><h1>Cuadrante del equipo</h1><p>Toca una celda para {isSupervisor?'editar, cambiar de profesional o añadir un turno':'consultar los turnos'}.</p></div><div className="month-switch"><button aria-label="Mes anterior" disabled={key<='2026-10'} onClick={()=>setMonth(addMonths(month,-1))}><ChevronLeft/></button><strong>{format(month,'MMMM yyyy',{locale:es})}</strong><button aria-label="Mes siguiente" disabled={key>='2026-12'} onClick={()=>setMonth(addMonths(month,1))}><ChevronRight/></button></div></div><div className="calendar-toolbar"><label>Mostrar<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">Todo el equipo</option>{profile.role==='professional'&&<option value={profile.id}>Mi cuadrante</option>}{staff.filter(s=>s.id!==profile.id).map(s=><option key={s.id} value={s.id}>{s.display_name}</option>)}</select></label>{isSupervisor&&<button className="primary" onClick={()=>onSelect({date:format(month,'yyyy-MM-01')})}><Plus size={17}/> Asignar turno</button>}</div><div className="planning-actions"><button className="soft-button" onClick={()=>setShowAbsences(true)}><CalendarOff size={17}/>{isSupervisor?'Ver ausencias':'Mis ausencias'}</button>{isSupervisor&&<button className="soft-button" onClick={()=>setShowCopy(true)}><Copy size={17}/> Copiar semana o selección</button>}<button className="soft-button" disabled={pdfBusy} onClick={()=>void exportPdf()}><Download size={17}/>{pdfBusy?'Preparando PDF…':'Descargar mes en PDF'}</button></div>{pdfMessage&&<p role="alert" className="form-message">{pdfMessage}</p>}{showCopy&&<CopySchedule month={key} assignments={assignments} consultations={consultations} profiles={coverageProfiles} requests={requests} staff={staff} onClose={()=>setShowCopy(false)} onCopy={onCopy}/>}
 {isSupervisor&&monthIssues.length>0&&<div className="panel compact-coverage"><button className="coverage-toggle" onClick={()=>setShowIssues(!showIssues)}><AlertTriangle size={18}/><strong>{monthIssues.length} incidencias de cobertura este mes</strong><span>{showIssues?'Ocultar':'Revisar'}</span></button>{showIssues&&<div className="coverage-detail-list">{monthIssues.map(i=><article className={`priority-item ${i.severity}`} key={i.id}><div><strong>{i.title}</strong><small>{format(parseISO(i.date),'d MMM',{locale:es})} · {i.detail}</small></div><button className="soft-button" onClick={()=>onSelect({date:i.date,consultationId:i.consultationId,startTime:i.startTime,endTime:i.endTime})}>{i.kind==='suspended'?'Revisar turno':'Asignar profesional'}</button></article>)}</div>}</div>}
 <div className="legend">{consultations.map(c=><span key={c.id} title={c.label}><i style={{background:c.color}}/>{c.short_label}</span>)}<span className="holiday-key"><i/>Festivo</span></div><div className="matrix-wrap"><div className="month-matrix" style={{gridTemplateColumns:`150px repeat(${days.length}, minmax(34px, 1fr))`}}><div className="matrix-corner">Profesional</div>{days.map(d=>{const date=format(d,'yyyy-MM-dd');const n=issues.filter(i=>i.date===date).length;return <button key={date} ref={date===focusDate?focusedDay:undefined} className={`day-head ${getDay(d)%6===0?'weekend':''} ${HOLIDAYS[date]?'holiday':''} ${n?'coverage-day':''} ${date===focusDate?'focused-day':''}`} title={`${format(d,'EEEE d MMM',{locale:es})}${HOLIDAYS[date]?` · ${HOLIDAYS[date]}`:''}${n?` · ${n} incidencias`:''}`} onClick={()=>onSelect({date})}><small>{format(d,'EEE',{locale:es}).slice(0,1)}</small><strong>{format(d,'d')}</strong>{n>0&&<b>{n}</b>}</button>})}{staff.filter(s=>filter==='all'||s.id===filter).map(p=><div key={p.id} style={{display:'contents'}}><div className={`staff-cell ${p.id===profile.id?'mine':''}`}><img src={MASCOTS.find(m=>m.key===p.mascot_key)?.src} alt=""/><span>{p.display_name}</span>{p.weekly_minutes<2100&&<small>Reducción 1/3</small>}</div>{days.map(d=>{const date=format(d,'yyyy-MM-dd');const items=assignments.filter(a=>a.professional_id===p.id&&a.work_date===date);const closed=getDay(d)%6===0||Boolean(HOLIDAYS[date]);return <button key={date} aria-label={`${p.display_name}, ${date}: ${items.length?items.map(a=>consultations.find(c=>c.id===a.consultation_id)?.label).join(', '):'sin turnos'}`} className={`shift-cell ${closed?'closed':''} ${isSameDay(d,new Date())?'today':''} ${date===focusDate?'focused-day':''}`} onClick={()=>onSelect({date,personId:p.id})}>{items.slice(0,2).map(a=><span key={a.id} className={a.provisional?'provisional':''} style={{'--chip':consultations.find(c=>c.id===a.consultation_id)?.color??'#688'} as React.CSSProperties}>{consultations.find(c=>c.id===a.consultation_id)?.short_label??a.consultation_id}</span>)}{items.length>2&&<em>+{items.length-2}</em>}</button>})}</div>)}</div></div><p className="calendar-note">Octubre–diciembre de 2026 · Las asignaciones pueden ser provisionales. Las alertas siguen las reglas editables de cada consulta.</p></section>
}
