import { useState } from 'react'
import { Check, Pencil, Plus, X } from 'lucide-react'
import type { Consultation, CoverageRule } from '../types'
import { defaultCoverageRules } from '../lib/scheduling'
import { supabase } from '../lib/supabase'
const days = ['D','L','M','X','J','V','S']
const newRule = (): CoverageRule => ({id:crypto.randomUUID(),weekdays:[1,2,3,4,5],start_time:'08:00',end_time:'15:00',min_staff:1,every_weeks:1,anchor_date:'2026-09-28',monthly:false,valid_from:'2026-10-01',valid_until:'2026-12-31',suspensions:[]})
export default function ConsultationManager({consultations,demo,onChange,reload}:{consultations:Consultation[];demo:boolean;onChange:React.Dispatch<React.SetStateAction<Consultation[]>>;reload:()=>void}) {
 const [draft,setDraft]=useState<Consultation|null>(null)
 const [isNew,setIsNew]=useState(false)
 const [message,setMessage]=useState('')
 const [busy,setBusy]=useState(false)
 const open=(c?:Consultation)=>{setMessage('');setIsNew(!c);setDraft(c?{...c,coverage_rules:structuredClone(c.coverage_rules??defaultCoverageRules(c.id))}:{id:`CONS_${crypto.randomUUID().slice(0,8)}`,label:'',short_label:'',color:'#3a7d63',active:true,default_start_time:'08:00',default_end_time:'15:00',coverage_rules:[newRule()]})}
 const changeRule=(index:number,patch:Partial<CoverageRule>)=>setDraft(d=>d?{...d,coverage_rules:d.coverage_rules!.map((r,i)=>i===index?{...r,...patch}:r)}:d)
 const save=async(e:React.FormEvent)=>{e.preventDefault();if(!draft)return;setMessage('');
   if(draft.coverage_rules!.some(r=>!r.weekdays.length||r.start_time>=r.end_time||r.valid_from>r.valid_until||r.suspensions.some(s=>!s.from||!s.to||s.from>s.to))){setMessage('Revisa los días seleccionados, el horario y las fechas de cada regla.');return}
   if(!draft.coverage_rules!.length&&!window.confirm('Esta consulta no tendrá alertas automáticas de cobertura. ¿Guardar así?'))return
   setBusy(true)
   const content={label:draft.label.trim(),short_label:draft.short_label.trim().toUpperCase(),color:draft.color,default_start_time:draft.default_start_time,default_end_time:draft.default_end_time,coverage_rules:draft.coverage_rules}
   if(demo)onChange(items=>isNew?[...items,{...draft,...content}]:items.map(c=>c.id===draft.id?{...c,...content}:c))
   else {const {error}=isNew?await supabase!.from('et_consultations').insert({...content,id:draft.id,active:true,sort_order:consultations.length*10+10}):await supabase!.from('et_consultations').update(content).eq('id',draft.id);if(error){setMessage(error.message);setBusy(false);return}await reload()}
   setBusy(false);setDraft(null)
 }
 return <section className="panel consultation-manager"><div className="section-heading"><div><h2>Consultas y cobertura</h2><p>Define cuándo abre cada consulta y cuántas personas necesita.</p></div><button className="primary" onClick={()=>open()}><Plus size={17}/> Añadir nueva consulta</button></div><div className="consultation-cards">{consultations.map(c=><article key={c.id}><span className="consultation-dot" style={{background:c.color}}/><div><strong>{c.label}</strong><small>{c.short_label} · {c.default_start_time?.slice(0,5)??'08:00'}–{c.default_end_time?.slice(0,5)??'15:00'}</small><small>{(c.coverage_rules??defaultCoverageRules(c.id)).length} reglas de cobertura{c.id==='PAAF'?' · Cobertura compartida con PF':''}</small></div><button className="soft-button" onClick={()=>open(c)}><Pencil size={15}/> Editar</button></article>)}</div>
 {draft&&<div className="modal-backdrop"><div className="modal wide-modal" role="dialog" aria-modal="true" aria-label={isNew?'Nueva consulta':'Editar consulta'}><button className="modal-close" aria-label="Cerrar" onClick={()=>setDraft(null)}><X/></button><h2>{isNew?'Nueva consulta':'Editar consulta'}</h2><form onSubmit={save}><div className="form-grid"><label>Nombre<input required minLength={2} maxLength={80} value={draft.label} onChange={e=>setDraft({...draft,label:e.target.value})}/></label><label>Abreviatura<input required maxLength={5} value={draft.short_label} onChange={e=>setDraft({...draft,short_label:e.target.value})}/></label><label>Color<input type="color" value={draft.color} onChange={e=>setDraft({...draft,color:e.target.value})}/></label><label>Horario al crear un turno<select value={draft.default_start_time?.slice(0,5)} onChange={e=>setDraft({...draft,default_start_time:e.target.value,default_end_time:e.target.value==='08:00'?'15:00':'20:00'})}><option value="08:00">Mañana · 8:00–15:00</option><option value="15:00">Tarde · 15:00–20:00</option></select></label></div><h3>¿Cuándo debe estar cubierta?</h3><p className="helper">Cada regla define una franja. Puedes añadir mañanas, tardes y cadencias distintas. Cambiar una regla no modifica turnos ya asignados.</p>
 {draft.coverage_rules!.map((r,i)=><fieldset className="rule-editor" key={r.id}><legend>Regla {i+1}</legend><div className="weekday-picker">{[1,2,3,4,5,6,0].map(day=><label key={day}><input type="checkbox" checked={r.weekdays.includes(day)} onChange={e=>changeRule(i,{weekdays:e.target.checked?[...r.weekdays,day]:r.weekdays.filter(d=>d!==day)})}/>{days[day]}</label>)}</div><div className="form-grid"><label>Desde<input required type="time" value={r.start_time} onChange={e=>changeRule(i,{start_time:e.target.value})}/></label><label>Hasta<input required type="time" value={r.end_time} onChange={e=>changeRule(i,{end_time:e.target.value})}/></label><label>Profesionales necesarios<input required type="number" min={1} max={20} value={r.min_staff} onChange={e=>changeRule(i,{min_staff:Number(e.target.value)})}/></label><label>Frecuencia<select value={r.monthly?'monthly':String(r.every_weeks)} onChange={e=>changeRule(i,{monthly:e.target.value==='monthly',every_weeks:e.target.value==='monthly'?1:Number(e.target.value)})}><option value="1">Todas las semanas</option><option value="2">Cada 2 semanas</option><option value="3">Cada 3 semanas</option><option value="4">Cada 4 semanas</option><option value="monthly">Una vez al mes</option></select></label>{!r.monthly&&r.every_weeks>1&&<label>Una fecha de la semana activa<input required type="date" value={r.anchor_date} onChange={e=>changeRule(i,{anchor_date:e.target.value})}/></label>}<label>Vigente desde<input required type="date" value={r.valid_from} onChange={e=>changeRule(i,{valid_from:e.target.value})}/></label><label>Vigente hasta<input required type="date" min={r.valid_from} value={r.valid_until} onChange={e=>changeRule(i,{valid_until:e.target.value})}/></label></div><p className="helper">{r.monthly?'Se exige una sesión cubierta al mes en alguno de los días seleccionados.':'La cobertura debe mantenerse durante toda la franja.'} Los festivos configurados se excluyen.</p>
 {!!r.alternatives?.length&&<p className="helper">Cobertura compartida con: {r.alternatives.join(', ')}. Una asignación en cualquiera de estas consultas cuenta para esta regla.</p>}
 <strong>Periodos suspendidos</strong>{r.suspensions.map((s,j)=><div className="suspension-row" key={j}><label>Desde<input required type="date" value={s.from} onChange={e=>changeRule(i,{suspensions:r.suspensions.map((x,k)=>k===j?{...x,from:e.target.value}:x)})}/></label><label>Hasta<input required type="date" min={s.from} value={s.to} onChange={e=>changeRule(i,{suspensions:r.suspensions.map((x,k)=>k===j?{...x,to:e.target.value}:x)})}/></label><button type="button" className="text-button inline" onClick={()=>changeRule(i,{suspensions:r.suspensions.filter((_,k)=>k!==j)})}>Quitar periodo</button></div>)}<div className="inline-actions"><button type="button" className="soft-button" onClick={()=>changeRule(i,{suspensions:[...r.suspensions,{from:'',to:''}]})}>Añadir suspensión</button><button type="button" className="text-button inline" onClick={()=>setDraft({...draft,coverage_rules:draft.coverage_rules!.filter((_,k)=>k!==i)})}>Quitar regla</button></div></fieldset>)}
 <button type="button" className="soft-button" onClick={()=>setDraft({...draft,coverage_rules:[...draft.coverage_rules!,newRule()]})}><Plus size={16}/> Añadir franja o regla</button>{message&&<p role="alert" className="form-message">{message}</p>}<div className="modal-footer"><button type="button" className="soft-button" onClick={()=>setDraft(null)}>Cancelar</button><button className="primary" disabled={busy}><Check size={17}/>{busy?'Guardando…':'Guardar consulta y reglas'}</button></div></form></div></div>}
 </section>
}
