import { usePlanning, getPlanning } from '../lib/planningConfig'
import { useState } from 'react'
import { Check, Pencil, Plus, X } from 'lucide-react'
import type { Consultation, CoverageRule, Staff } from '../types'
import { defaultCoverageRules } from '../lib/scheduling'
import { supabase } from '../lib/supabase'

const days = ['D','L','M','X','J','V','S']
const dayNames=['domingo','lunes','martes','miércoles','jueves','viernes','sábado']
const FOREVER='9999-12-31'
const newRule = (): CoverageRule => ({id:crypto.randomUUID(),weekdays:[1,2,3,4,5],start_time:'08:00',end_time:'15:00',min_staff:1,every_weeks:1,anchor_date:getPlanning().start_date,monthly:false,valid_from:getPlanning().start_date,valid_until:FOREVER,suspensions:[],preferred_staff_ids:[],secondary_staff_ids:[]})

function normalizeRules(c:Consultation){
 const preferred=c.preferred_staff_id?[c.preferred_staff_id]:[]
 const secondary=c.secondary_staff_ids??[]
 return structuredClone(c.coverage_rules??defaultCoverageRules(c.id)).map(r=>({
  ...r,
  preferred_staff_ids:r.preferred_staff_ids?.length?r.preferred_staff_ids:preferred,
  secondary_staff_ids:r.secondary_staff_ids?.length?r.secondary_staff_ids:secondary.filter(id=>!preferred.includes(id)),
 }))
}
function names(ids:string[]|undefined,staff:Staff[]){return (ids??[]).map(id=>staff.find(p=>p.id===id)?.display_name??'No disponible').join(' + ')}
function ruleSummary(r:CoverageRule,staff:Staff[]){
 const ds=r.weekdays.map(d=>dayNames[d].slice(0,3)).join('·')
 const freq=r.monthly?'1/mes':r.every_weeks===1?'semanal':`cada ${r.every_weeks} sem.`
 const habitual=names(r.preferred_staff_ids,staff)||'Sin habitual'
 return `${ds} · ${r.start_time.slice(0,5)}–${r.end_time.slice(0,5)} · ${freq} · ${habitual}`
}

export default function ConsultationManager({staff,consultations,demo,onChange,reload}:{staff:Staff[];consultations:Consultation[];demo:boolean;onChange:React.Dispatch<React.SetStateAction<Consultation[]>>;reload:()=>void}) {
 const planning=usePlanning(); const {start_date:ROTA_START,end_date:ROTA_END}=planning
 const professionals=staff.filter(p=>p.active&&p.role==='professional')
 const [draft,setDraft]=useState<Consultation|null>(null)
 const [isNew,setIsNew]=useState(false)
 const [message,setMessage]=useState('')
 const [busy,setBusy]=useState(false)
 const open=(c?:Consultation)=>{setMessage('');setIsNew(!c);setDraft(c?{...c,coverage_rules:normalizeRules(c)}:{id:`CONS_${crypto.randomUUID().slice(0,8)}`,label:'',short_label:'',color:'#3a7d63',active:true,default_start_time:'08:00',default_end_time:'15:00',coverage_rules:[newRule()]})}
 const changeRule=(index:number,patch:Partial<CoverageRule>)=>setDraft(d=>d?{...d,coverage_rules:d.coverage_rules!.map((r,i)=>i===index?{...r,...patch}:r)}:d)
 const save=async(e:React.FormEvent)=>{e.preventDefault();if(!draft)return;setMessage('')
   const invalid=draft.coverage_rules!.find(r=>!r.weekdays.length||r.start_time>=r.end_time||r.valid_from>r.valid_until||!(r.preferred_staff_ids?.length)||(r.fallback_min_staff!==undefined&&(r.fallback_min_staff<1||r.fallback_min_staff>=r.min_staff))||r.suspensions.some(s=>!s.from||!s.to||s.from>s.to))
   if(invalid){setMessage('Revisa cada regla: días, horario, vigencia, profesionales habituales y que el mínimo permitido sea menor que los profesionales necesarios.');return}
   if(!draft.coverage_rules!.length&&!window.confirm('Esta consulta no tendrá alertas automáticas de cobertura. ¿Guardar así?'))return
   setBusy(true)
   const content={preferred_staff_id:null,secondary_staff_ids:[],label:draft.label.trim(),short_label:draft.short_label.trim().toUpperCase(),color:draft.color,default_start_time:draft.default_start_time,default_end_time:draft.default_end_time,coverage_rules:draft.coverage_rules}
   if(demo)onChange(items=>isNew?[...items,{...draft,...content}]:items.map(c=>c.id===draft.id?{...c,...content}:c))
   else {const {error}=isNew?await supabase!.from('et_consultations').insert({...content,id:draft.id,active:true,sort_order:consultations.length*10+10}):await supabase!.from('et_consultations').update(content).eq('id',draft.id);if(error){setMessage(error.message);setBusy(false);return}await reload()}
   setBusy(false);setDraft(null)
 }
 return <section className="panel consultation-manager"><div className="section-heading"><div><h2>Consultas y cobertura</h2><p>Cada regla reúne días, horario, frecuencia y quién suele cubrir esa franja.</p></div><button className="primary" onClick={()=>open()}><Plus size={17}/> Añadir nueva consulta</button></div><div className="consultation-cards">{consultations.map(c=>{const rules=normalizeRules(c);return <article key={c.id}><span className="consultation-dot" style={{background:c.color}}/><div><strong>{c.label}</strong><small>{c.short_label} · {c.default_start_time?.slice(0,5)??'08:00'}–{c.default_end_time?.slice(0,5)??'15:00'}</small>{rules.some(r=>r.valid_from>ROTA_START||(r.valid_until!==FOREVER&&r.valid_until<ROTA_END))&&<small className="review-text">Revisar vigencia: alguna regla no abarca todo el periodo.</small>}<div className="coverage-summary">{rules.map((r,i)=><small key={r.id}><b>R{i+1}</b> {ruleSummary(r,staff)}</small>)}</div><small>{rules.length} reglas de cobertura{c.id==='PAAF'?' · Cobertura compartida con PF':''}</small></div><button className="soft-button" onClick={()=>open(c)}><Pencil size={15}/> Editar</button></article>})}</div>
 {draft&&<div className="modal-backdrop"><div className="modal wide-modal" role="dialog" aria-modal="true" aria-label={isNew?'Nueva consulta':'Editar consulta'}><button className="modal-close" aria-label="Cerrar" onClick={()=>setDraft(null)}><X/></button><h2>{isNew?'Nueva consulta':'Editar consulta'}</h2><form onSubmit={save}><div className="form-grid"><label>Nombre<input required minLength={2} maxLength={80} value={draft.label} onChange={e=>setDraft({...draft,label:e.target.value})}/></label><label>Abreviatura<input required maxLength={5} value={draft.short_label} onChange={e=>setDraft({...draft,short_label:e.target.value})}/></label><label>Color<input type="color" value={draft.color} onChange={e=>setDraft({...draft,color:e.target.value})}/></label><label>Horario al crear un turno<select value={draft.default_start_time?.slice(0,5)} onChange={e=>setDraft({...draft,default_start_time:e.target.value,default_end_time:e.target.value==='08:00'?'15:00':'20:00'})}><option value="08:00">Mañana · 8:00–15:00</option><option value="15:00">Tarde · 15:00–20:00</option></select></label></div><h3>¿Cuándo debe estar cubierta?</h3><p className="helper">Cada regla es una unidad completa de planificación: franja, frecuencia, profesionales necesarios, habituales y alternativas. Así una misma consulta puede tener responsables distintos según el día.</p>
 {draft.coverage_rules!.map((r,i)=><fieldset className="rule-editor" key={r.id}><legend>Regla {i+1}</legend><div className="weekday-picker">{[1,2,3,4,5,6,0].map(day=><label key={day}><input type="checkbox" checked={r.weekdays.includes(day)} onChange={e=>changeRule(i,{weekdays:e.target.checked?[...r.weekdays,day]:r.weekdays.filter(d=>d!==day)})}/>{days[day]}</label>)}</div><div className="form-grid"><label>Desde<input required type="time" value={r.start_time} onChange={e=>changeRule(i,{start_time:e.target.value})}/></label><label>Hasta<input required type="time" value={r.end_time} onChange={e=>changeRule(i,{end_time:e.target.value})}/></label><label>Profesionales necesarios<input required type="number" min={1} max={20} value={r.min_staff} onChange={e=>changeRule(i,{min_staff:Number(e.target.value)})}/></label><label className="coverage-reduced-toggle"><span>Permitir cobertura reducida si no es posible</span><input type="checkbox" checked={r.fallback_min_staff!==undefined} disabled={r.min_staff<=1} onChange={e=>changeRule(i,{fallback_min_staff:e.target.checked?Math.max(1,r.min_staff-1):undefined})}/></label>{r.fallback_min_staff!==undefined&&<label>Mínimo permitido<input required type="number" min={1} max={Math.max(1,r.min_staff-1)} value={r.fallback_min_staff} onChange={e=>changeRule(i,{fallback_min_staff:Number(e.target.value)})}/></label>}<label>Frecuencia<select value={r.monthly?'monthly':String(r.every_weeks)} onChange={e=>changeRule(i,{monthly:e.target.value==='monthly',every_weeks:e.target.value==='monthly'?1:Number(e.target.value)})}><option value="1">Todas las semanas</option><option value="2">Cada 2 semanas</option><option value="3">Cada 3 semanas</option><option value="4">Cada 4 semanas</option><option value="monthly">Una vez al mes</option></select></label>{!r.monthly&&r.every_weeks>1&&<label>Una fecha de la semana activa<input required type="date" value={r.anchor_date} onChange={e=>changeRule(i,{anchor_date:e.target.value})}/></label>}<label>Vigente desde<input required type="date" value={r.valid_from} onChange={e=>changeRule(i,{valid_from:e.target.value})}/></label><label>Vigente hasta<div className="cadence-until"><select aria-label="Tipo de fin de vigencia" value={r.valid_until===FOREVER?'always':'date'} onChange={e=>changeRule(i,{valid_until:e.target.value==='always'?FOREVER:planning.end_date})}><option value="date">Hasta una fecha</option><option value="always">SIEMPRE</option></select>{r.valid_until!==FOREVER&&<input required type="date" min={r.valid_from} value={r.valid_until} onChange={e=>changeRule(i,{valid_until:e.target.value})}/>} {r.valid_until===FOREVER&&<strong className="always-badge">SIEMPRE</strong>}</div></label></div>
 <div className="rule-staff-block"><strong>Profesional/es habitual/es</strong><p className="helper">Primera opción de “Sugerir cuadrante”. Puedes marcar varios si esta regla necesita más de una persona.</p><div className="secondary-picker">{professionals.map(p=><label key={p.id}><input type="checkbox" checked={r.preferred_staff_ids?.includes(p.id)??false} onChange={e=>{const preferred=e.target.checked?[...(r.preferred_staff_ids??[]),p.id]:(r.preferred_staff_ids??[]).filter(id=>id!==p.id);changeRule(i,{preferred_staff_ids:preferred,secondary_staff_ids:(r.secondary_staff_ids??[]).filter(id=>!preferred.includes(id))})}}/>{p.display_name}</label>)}</div>
 <strong>Alternativas si no están disponibles</strong><p className="helper">Opcional. Se intentarán después de los habituales y antes del resto de profesionales compatibles.</p><div className="secondary-picker">{professionals.filter(p=>!(r.preferred_staff_ids??[]).includes(p.id)).map(p=><label key={p.id}><input type="checkbox" checked={r.secondary_staff_ids?.includes(p.id)??false} onChange={e=>changeRule(i,{secondary_staff_ids:e.target.checked?[...(r.secondary_staff_ids??[]),p.id]:(r.secondary_staff_ids??[]).filter(id=>id!==p.id)})}/>{p.display_name}</label>)}</div></div>
 <p className="rule-readable-summary"><b>Resumen:</b> {ruleSummary(r,staff)}{(r.secondary_staff_ids?.length??0)>0?` · Alternativas: ${names(r.secondary_staff_ids,staff)}`:''}</p>
 <p className="helper">{r.monthly?'Se exige una sesión cubierta al mes en alguno de los días seleccionados.':'La cobertura debe mantenerse durante toda la franja.'}{r.fallback_min_staff!==undefined?` Se intentarán ${r.min_staff} profesionales y, si no es posible, se aceptará un mínimo de ${r.fallback_min_staff} sin generar incidencia.`:''} Los festivos configurados se excluyen.</p>
 {!!r.alternatives?.length&&<p className="helper">Cobertura compartida con: {r.alternatives.join(', ')}. Una asignación en cualquiera de estas consultas cuenta para esta regla.</p>}
 <strong>Periodos suspendidos</strong>{r.suspensions.map((s,j)=><div className="suspension-row" key={j}><label>Desde<input required type="date" value={s.from} onChange={e=>changeRule(i,{suspensions:r.suspensions.map((x,k)=>k===j?{...x,from:e.target.value}:x)})}/></label><label>Hasta<input required type="date" min={s.from} value={s.to} onChange={e=>changeRule(i,{suspensions:r.suspensions.map((x,k)=>k===j?{...x,to:e.target.value}:x)})}/></label><button type="button" className="text-button inline" onClick={()=>changeRule(i,{suspensions:r.suspensions.filter((_,k)=>k!==j)})}>Quitar periodo</button></div>)}<div className="inline-actions"><button type="button" className="soft-button" onClick={()=>changeRule(i,{suspensions:[...r.suspensions,{from:'',to:''}]})}>Añadir suspensión</button><button type="button" className="text-button inline" onClick={()=>setDraft({...draft,coverage_rules:draft.coverage_rules!.filter((_,k)=>k!==i)})}>Quitar regla</button></div></fieldset>)}
 <button type="button" className="soft-button" onClick={()=>setDraft({...draft,coverage_rules:[...draft.coverage_rules!,newRule()]})}><Plus size={16}/> Añadir franja o regla</button>{message&&<p role="alert" className="form-message">{message}</p>}<div className="modal-footer"><button type="button" className="soft-button" onClick={()=>setDraft(null)}>Cancelar</button><button className="primary" disabled={busy}><Check size={17}/>{busy?'Guardando…':'Guardar consulta y reglas'}</button></div></form></div></div>}
 </section>
}
