import { useEffect, useState } from 'react'
import { ArrowDown, ArrowUp, Check, Plus, Trash2 } from 'lucide-react'
import type { Consultation, CoverageProfile, Staff } from '../types'
import { supabase } from '../lib/supabase'
export default function CoveragePreferences({person,consultations,profile,demo,onChange,reload}:{person:Staff;consultations:Consultation[];profile?:CoverageProfile;demo:boolean;onChange:React.Dispatch<React.SetStateAction<CoverageProfile[]>>;reload:()=>void}){
 const [ids,setIds]=useState<string[]>(profile?.consultation_ids??[]);const [chosen,setChosen]=useState('');const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const [dirty,setDirty]=useState(false)
 useEffect(()=>{setIds(profile?.consultation_ids??[]);setChosen('');setDirty(false);setMessage('')},[person.id])
 const edit=(next:string[])=>{setIds(next);setDirty(true);setMessage('')}
 const move=(i:number,d:number)=>{const next=[...ids];[next[i],next[i+d]]=[next[i+d],next[i]];edit(next)}
 const save=async()=>{setBusy(true);setMessage('');const next={staff_id:person.id,consultation_ids:ids};if(demo)onChange(rows=>[...rows.filter(r=>r.staff_id!==person.id),next]);else{const {error}=await supabase!.from('et_staff_coverage').upsert(next,{onConflict:'staff_id'});if(error){setBusy(false);setMessage(error.message);return}await reload()}setDirty(false);setBusy(false);setMessage('Lista de consultas guardada.')}
 return <section className="panel preferences-panel"><h2>Consultas que puedo cubrir</h2><p>Añade solo las que puedes cubrir y ordénalas por prioridad. La primera será tu opción preferente; no es necesario completar todas.</p><p className="helper">{!profile?'Pendiente de configurar. No se te propondrá automáticamente hasta guardar tu lista.':!profile.consultation_ids.length?'Lista guardada sin consultas disponibles.':'Esta lista se utiliza para buscar coberturas. Supervisión también puede revisarla.'}</p><ol className="preference-list">{ids.map((id,i)=><li key={id}><span className="priority-number">{i+1}</span><strong>{consultations.find(c=>c.id===id)?.label??id}</strong><div className="inline-actions"><button type="button" disabled={i===0||busy} aria-label={`Subir ${id}`} className="soft-button" onClick={()=>move(i,-1)}><ArrowUp size={16}/></button><button type="button" disabled={i===ids.length-1||busy} aria-label={`Bajar ${id}`} className="soft-button" onClick={()=>move(i,1)}><ArrowDown size={16}/></button><button type="button" disabled={busy} className="text-button inline danger-text" onClick={()=>edit(ids.filter(x=>x!==id))}><Trash2 size={15}/> Quitar</button></div></li>)}</ol><div className="preference-add"><label>Añadir consulta<select value={chosen} onChange={e=>setChosen(e.target.value)}><option value="">Selecciona una consulta</option>{consultations.filter(c=>c.active&&!ids.includes(c.id)).map(c=><option value={c.id} key={c.id}>{c.label}</option>)}</select></label><button type="button" disabled={!chosen||busy} className="soft-button" onClick={()=>{edit([...ids,chosen]);setChosen('')}}><Plus size={16}/> Añadir</button></div>{dirty&&<p className="helper">Cambios pendientes de guardar.</p>}{message&&<p className="form-message" role="status">{message}</p>}<button type="button" className="primary" disabled={busy} onClick={()=>void save()}><Check size={16}/>{busy?'Guardando…':'Guardar orden de consultas'}</button></section>
}
