import { useRef, useState } from 'react'
import { X } from 'lucide-react'
import { format, parseISO } from 'date-fns'
import { es } from 'date-fns/locale'
import type { CoverageIssue } from '../lib/coverage'
import type { CoverageException } from '../types'
export function ExceptionDialog({issue,onSave,onClose}:{issue:CoverageIssue;onSave:(reason:string)=>Promise<string|null>;onClose:()=>void}) {
 const [reason,setReason]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');const saving=useRef(false)
 async function save(e:React.FormEvent){e.preventDefault();if(saving.current||reason.trim().length<3)return;saving.current=true;setBusy(true);setError('');try{const result=await onSave(reason.trim());if(result)setError(result);else onClose()}catch{setError('No se ha podido guardar la excepción. Inténtalo de nuevo.')}finally{saving.current=false;setBusy(false)}}
 return <div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-labelledby="exception-title"><button className="modal-close" aria-label="Cerrar excepción" disabled={busy} onClick={onClose}><X/></button><h2 id="exception-title">Añadir excepción de Planta</h2><p>{format(parseISO(issue.date),'EEEE d MMMM',{locale:es})} · {issue.startTime}–{issue.endTime}</p><p>Se acepta una enfermera en esta franja y se da por resuelta esta incidencia. Si Planta queda sin cobertura o cambia la regla, la incidencia volverá a mostrarse.</p><form onSubmit={save}><label>Motivo de la excepción<textarea autoFocus required minLength={3} maxLength={1000} value={reason} onChange={e=>setReason(e.target.value)} placeholder="Explica por qué no es posible cubrir con dos enfermeras"/></label>{error&&<p role="alert" className="form-message">{error}</p>}<div className="modal-footer"><button type="button" className="soft-button" disabled={busy} onClick={onClose}>Cancelar</button><button className="primary" disabled={busy||reason.trim().length<3}>{busy?'Guardando…':'Guardar excepción y resolver'}</button></div></form></section></div>
}
export function ExceptionRegister({exceptions,onRevoke}:{exceptions:CoverageException[];onRevoke:(id:string)=>Promise<string|null>}) {
 const [busy,setBusy]=useState<string|null>(null);const [error,setError]=useState('')
 async function revoke(id:string){if(busy)return;if(!window.confirm('¿Retirar esta excepción? La cobertura se revisará de nuevo.'))return;setBusy(id);setError('');try{setError(await onRevoke(id)??'')}catch{setError('No se ha podido retirar la excepción.')}finally{setBusy(null)}}
 return <details className="panel exception-register"><summary>Excepciones de Planta ({exceptions.length})</summary><p className="helper">Solo resuelven la incidencia del día y la regla indicados cuando queda una enfermera durante toda la franja.</p>{error&&<p role="alert">{error}</p>}{!exceptions.length&&<p>No hay excepciones registradas.</p>}{exceptions.map(e=><article key={e.id}><div><strong>{format(parseISO(e.work_date),'d MMM yyyy',{locale:es})} · {e.rule_snapshot.start_time}–{e.rule_snapshot.end_time}</strong><p className="exception-reason">{e.reason}</p><small>{e.created_by_name} · {format(parseISO(e.created_at),'d MMM yyyy · HH:mm',{locale:es})} · {e.revoked_at?'Retirada':'Autorizada'}</small></div>{!e.revoked_at&&<button className="soft-button" disabled={busy!==null} onClick={()=>void revoke(e.id)}>{busy===e.id?'Retirando…':'Retirar excepción'}</button>}</article>)}</details>
}
