import { useState } from 'react'
import { History, Undo2 } from 'lucide-react'
import { format, parseISO } from 'date-fns'
import { es } from 'date-fns/locale'
import type { Assignment, AssignmentHistory, Consultation, ShiftRequest, Staff } from '../types'
import { assignmentConflicts } from '../lib/scheduling'
export default function HistoryPanel({history,staff,consultations,assignments,requests,onUndo}:{history:AssignmentHistory[];staff:Staff[];consultations:Consultation[];assignments:Assignment[];requests:ShiftRequest[];onUndo:(h:AssignmentHistory,reason:string|null)=>Promise<string|null>}) {
 const [message,setMessage]=useState('');const [busy,setBusy]=useState(false)
 const describe=(a:Assignment|null)=>a?`${staff.find(s=>s.id===a.professional_id)?.display_name??'Profesional'} · ${consultations.find(c=>c.id===a.consultation_id)?.label??a.consultation_id} · ${format(parseISO(a.work_date),'d MMM',{locale:es})} · ${a.start_time.slice(0,5)}–${a.end_time.slice(0,5)}`:'Sin asignación'
 const undo=async(h:AssignmentHistory)=>{let reason:string|null=null;const conflicts=h.before_data?assignmentConflicts(h.before_data,assignments,requests,consultations):[];if(conflicts.length){reason=window.prompt(`${conflicts.join('\n')}\n\nPara restaurar este turno como excepción, escribe el motivo (mínimo 5 caracteres).`);if(!reason||reason.trim().length<5)return}if(!window.confirm(`¿Deshacer este cambio?\n\nQuedará: ${describe(h.before_data)}`))return;setBusy(true);const error=await onUndo(h,reason);setMessage(error??'Cambio deshecho. La restauración también queda registrada.');setBusy(false)}
 return <section className="content-section"><div className="section-heading"><div><span className="eyebrow">Cambios trazables</span><h1>Historial del cuadrante</h1><p>Últimos 100 cambios desde la activación de esta función. Solo se puede deshacer la versión más reciente de cada turno.</p></div><History/></div>{message&&<p className="form-message" role="status">{message}</p>}<div className="history-list">{history.map((h,index)=>{const latest=!history.slice(0,index).some(x=>x.assignment_id===h.assignment_id);return <article className="panel" key={h.id}><div className="history-meta"><strong>{h.action==='INSERT'?'Turno añadido':h.action==='DELETE'?'Turno eliminado':'Turno modificado'}</strong><small>{h.actor_name} · {format(parseISO(h.changed_at),'d MMM · HH:mm:ss',{locale:es})}</small></div><p><strong>Antes:</strong> {describe(h.before_data)}</p><p><strong>Después:</strong> {describe(h.after_data)}</p>{h.after_data?.override_reason&&<p className="exception-note">Excepción: {h.after_data.override_reason}</p>}{latest?<button disabled={busy} className="soft-button" onClick={()=>void undo(h)}><Undo2 size={16}/> Deshacer cambio</button>:<small>Hay un cambio posterior en este turno.</small>}</article>})}{!history.length&&<div className="empty-state panel"><History/><p>Los próximos cambios en turnos aparecerán aquí.</p></div>}</div></section>
}
