import {useState} from 'react'
import {format,parseISO} from 'date-fns'
import {es} from 'date-fns/locale'
import {usePlanning,getPlanning,monthRange,validatePlanning,type PlanningConfig} from '../lib/planningConfig'
export default function PlanningSettings({onSave}:{onSave:(config:PlanningConfig)=>Promise<string|null>}){
 const current=usePlanning()
 const [config,setConfig]=useState(current)
 const [first,setFirst]=useState(config.start_date.slice(0,7)),[last,setLast]=useState(config.end_date.slice(0,7))
 const [holidays,setHolidays]=useState({...config.holidays}),[date,setDate]=useState(''),[name,setName]=useState('')
 const [busy,setBusy]=useState(false),[message,setMessage]=useState('')
 const add=()=>{if(!date||!name.trim())return;setHolidays(h=>({...h,[date]:name.trim()}));setDate('');setName('');setMessage('Festivo añadido a la lista. Pulsa Guardar periodo y festivos para aplicarlo.')}
 const save=async(e:React.FormEvent)=>{e.preventDefault();if(busy)return;setMessage('');if(!first||!last){setMessage('Selecciona ambos meses.');return}const next={...config,...monthRange(first,last),holidays};const error=validatePlanning(next);if(error){setMessage(error);return}if(date||name){setMessage('Añade el festivo que estás escribiendo o vacía sus campos antes de guardar.');return}setBusy(true);try{const result=await onSave(next);if(!result)setConfig(getPlanning());setMessage(result??'Periodo y festivos guardados.')}catch{setMessage('No se han podido guardar los cambios. Inténtalo de nuevo.')}finally{setBusy(false)}}
 return <form className="panel planning-settings" onSubmit={save}><h2>Periodo y festivos</h2><p>Elige los meses disponibles para todo el equipo. Cambiar el periodo conserva los turnos guardados y las publicaciones de los demás meses.</p><div className="form-grid"><label>Primer mes<input type="month" required value={first} onChange={e=>setFirst(e.target.value)}/></label><label>Último mes<input type="month" required min={first} value={last} onChange={e=>setLast(e.target.value)}/></label></div><p className="helper">De 1 a 24 meses. Revisa en Consultas la vigencia de las reglas al ampliar el periodo.</p><section className="settings-holidays"><h3>Festivos contemplados</h3><p>Los festivos oficiales SAS/Andalucía y locales de Huelva de 2026 y 2027 están precargados. Se excluyen de la cobertura habitual y de la copia de turnos. Puedes añadir o ajustar otros días propios del servicio sin borrar los ya configurados.</p><div className="form-grid"><label>Fecha del festivo<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label>Nombre del festivo<input maxLength={100} value={name} onChange={e=>setName(e.target.value)}/></label></div><button type="button" className="soft-button" disabled={busy||!date||!name.trim()} onClick={add}>{date&&holidays[date]?'Actualizar festivo':'Añadir festivo'}</button><ul>{Object.entries(holidays).sort(([a],[b])=>a.localeCompare(b)).map(([d,n])=><li key={d}><time dateTime={d}>{format(parseISO(d),'d MMM yyyy',{locale:es})}</time><span>{n}</span><button type="button" className="text-button inline" disabled={busy} aria-label={`Quitar festivo ${d}`} onClick={()=>setHolidays(h=>Object.fromEntries(Object.entries(h).filter(([x])=>x!==d)))}>Quitar</button></li>)}</ul></section>{message&&<p className="form-message" role="status">{message}</p>}<button type="button" className="soft-button" disabled={busy} onClick={()=>{if(!window.confirm('¿Recargar la configuración guardada y descartar los cambios sin guardar?'))return;const c=getPlanning();setConfig(c);setFirst(c.start_date.slice(0,7));setLast(c.end_date.slice(0,7));setHolidays({...c.holidays});setDate('');setName('');setMessage('Configuración recargada.')}}>Recargar configuración</button><button className="primary" disabled={busy}>{busy?'Guardando…':'Guardar periodo y festivos'}</button></form>
}
