import { useEffect, useState } from 'react'
import { format, parseISO } from 'date-fns'
import { es } from 'date-fns/locale'
import { CheckCircle2, FilePenLine, Send, X } from 'lucide-react'
import type { Assignment, RotaPublication,LockedMonth } from '../types'
import { supabase } from '../lib/supabase'

export interface PublicationPreview { added:number; changed:number; removed:number; blocked:number; exceptions:number; provisional:number; fingerprint:string }
export function rotaChanges(draft:Assignment[], published:Assignment[], month:string) {
 const current=draft.filter(a=>a.work_date.startsWith(month)); const previous=published.filter(a=>a.work_date.startsWith(month))
 const fields=(a:Assignment)=>JSON.stringify([a.professional_id,a.work_date,a.consultation_id,a.start_time,a.end_time,a.notes??null,a.provisional,a.override_reason??null,a.is_extra??false])
 return {added:current.filter(a=>!previous.some(b=>b.id===a.id)).length, removed:previous.filter(a=>!current.some(b=>b.id===a.id)).length, changed:current.filter(a=>previous.some(b=>b.id===a.id&&fields(a)!==fields(b))).length}
}
export default function PublicationPanel({month,isSupervisor,draft,published,publication,locked,coverageCount,demo,onLock,onPublish}:{month:string;isSupervisor:boolean;draft:Assignment[];published:Assignment[];publication?:RotaPublication;locked?:LockedMonth;coverageCount:number;demo:boolean;onLock?:()=>Promise<string|null>;onPublish:(preview:PublicationPreview)=>Promise<string|null>}) {
 const [lockConfirm,setLockConfirm]=useState(false);const [preview,setPreview]=useState<PublicationPreview|null>(null);const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const [ack,setAck]=useState(false)
 useEffect(()=>{setPreview(null);setMessage('');setAck(false);setLockConfirm(false)},[month])
 const counts=rotaChanges(draft,published,month);const total=counts.added+counts.changed+counts.removed
 const review=async()=>{setBusy(true);setMessage('');setAck(false);try {
  if(demo){setPreview({...counts,blocked:0,exceptions:0,provisional:draft.filter(a=>a.work_date.startsWith(month)&&a.provisional).length,fingerprint:'demo'})}
  else {const {data,error}=await supabase!.rpc('et_preview_publication',{p_month:month+'-01'});if(error)throw error;setPreview(data as PublicationPreview)}
 }catch(error){setMessage(error instanceof Error?error.message:(error as {message?:string}).message??'No se ha podido preparar la revisión.')}finally{setBusy(false)}}
 const publish=async()=>{if(!preview)return;setBusy(true);setMessage('');try {const result=await onPublish(preview);if(result)setMessage(result);else setMessage('Cuadrante publicado. El equipo ya puede consultar esta versión.');setPreview(null)}catch(error){setPreview(null);setMessage(error instanceof Error?error.message:'No se ha podido confirmar la publicación. Actualiza la página antes de volver a intentarlo.')}finally{setBusy(false)}}
 const lock=async()=>{setBusy(true);setMessage('');try{const result=onLock?await onLock():'Bloqueo no disponible';setMessage(result??'Mes bloqueado permanentemente. El cuadrante queda en modo consulta.');if(!result)setLockConfirm(false)}catch(error){setMessage(error instanceof Error?error.message:'No se ha podido bloquear el mes. Actualiza y vuelve a intentarlo.')}finally{setBusy(false)}}
 return <section className={`publication-panel ${isSupervisor?'draft':'published'}`} aria-label="Estado de publicación"><div>{isSupervisor?<FilePenLine size={21}/>:<CheckCircle2 size={21}/>}<div><strong>{locked?'Mes bloqueado permanentemente':isSupervisor?'Borrador de supervisión':'Cuadrante publicado'}</strong><p>{locked?'Este mes está cerrado y solo se puede consultar.':isSupervisor?`${total} cambios pendientes de publicar. El equipo ve la última versión publicada.`:'Esta es la versión que supervisión ha compartido con el equipo.'}</p><small>{publication?`${publication.initial_snapshot?'Versión inicial conservada':'Última publicación'}: ${format(parseISO(publication.published_at),'dd/MM/yyyy · HH:mm')} · v${publication.version}`:'Este mes todavía no tiene una versión publicada.'}</small></div></div>{isSupervisor&&!locked&&<button className="primary" disabled={busy||!total} onClick={()=>void review()}><Send size={16}/>{busy?'Preparando…':'Revisar y publicar'}</button>}{isSupervisor&&!locked&&publication&&<button className="soft-button" disabled={busy||total>0} onClick={()=>setLockConfirm(true)}>Bloquear el mes permanentemente</button>}{message&&<p role="status" className="form-message">{message}</p>}
 {lockConfirm&&<div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-labelledby="lock-month-title"><button type="button" className="modal-close" disabled={busy} onClick={()=>setLockConfirm(false)} aria-label="Cerrar"><X/></button><h2 id="lock-month-title">Bloquear {format(parseISO(month+'-01'),'MMMM yyyy',{locale:es})}</h2><p>Esta acción es permanente. Después no se podrán añadir, editar, eliminar ni volver a publicar turnos de este mes. Comprueba que la última versión está publicada.</p>{message&&<p role="alert" className="form-message">{message}</p>}<div className="quick-actions"><button type="button" className="soft-button" disabled={busy} onClick={()=>setLockConfirm(false)}>Seguir revisando</button><button type="button" className="primary" disabled={busy} onClick={()=>void lock()}>{busy?'Bloqueando…':'Sí, bloquear permanentemente'}</button></div></section></div>}
 {preview&&<div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-labelledby="publication-title"><button className="modal-close" disabled={busy} onClick={()=>setPreview(null)} aria-label="Cerrar revisión"><X/></button><span className="eyebrow">Revisión antes de publicar</span><h2 id="publication-title">Publicar {format(parseISO(month+'-01'),'MMMM yyyy',{locale:es})}</h2><div className="publication-counts"><span><b>{preview.added}</b>Añadidos</span><span><b>{preview.changed}</b>Modificados</span><span><b>{preview.removed}</b>Eliminados</span></div><p>{preview.blocked} turnos con conflictos sin justificar · {preview.exceptions} excepciones justificadas.</p><p>{coverageCount} incidencias de cobertura · {preview.provisional} turnos provisionales.</p>{preview.blocked>0?<p role="alert" className="form-message">Resuelve o justifica los conflictos antes de publicar.</p>:<label className="publication-confirm"><input type="checkbox" checked={ack} onChange={e=>setAck(e.target.checked)}/>He revisado los cambios, la cobertura y las excepciones. Quiero compartir esta versión y avisar al equipo.</label>}<div className="quick-actions"><button className="soft-button" disabled={busy} onClick={()=>setPreview(null)}>Seguir editando</button><button className="primary" disabled={busy||!ack||preview.blocked>0} onClick={()=>void publish()}>{busy?'Publicando…':'Publicar cuadrante'}</button></div></section></div>}
 </section>
}
