import { useEffect, useRef, useState } from 'react'
import { Bell, Check, Pencil, Plus, Trash2, X } from 'lucide-react'
import { format, parseISO } from 'date-fns'
import { es } from 'date-fns/locale'
import type { Assignment, Consultation, RequestStatus, RequestType, ShiftRequest, Staff } from '../types'
import AbsenceImpact, { isAbsenceRequest } from './AbsenceImpact'
import { supabase } from '../lib/supabase'
const labels: Record<RequestType,string>={vacation:'Vacaciones',permission:'Permiso',swap:'Cambio con una compañera',preference:'Día u horario preferente',correction:'Corrección de una asignación'}
export default function RequestsPanel({requests,unreadIds,staff,profile,isSupervisor,demo,onChange,reload,assignments,focusId,consultations=[],publishedAssignments=[],onReassign,onCalendar}:{requests:ShiftRequest[];unreadIds:string[];staff:Staff[];profile:Staff;isSupervisor:boolean;demo:boolean;onChange:React.Dispatch<React.SetStateAction<ShiftRequest[]>>;reload:()=>void;assignments:Assignment[];focusId:string|null;consultations?:Consultation[];publishedAssignments?:Assignment[];onReassign?:(assignment:Assignment)=>void;onCalendar?:(date:string)=>void}) {
 const [tab,setTab]=useState<'received'|'sent'|'all'>(unreadIds.length ? 'all' : 'received')
 const [statusFilter,setStatusFilter]=useState('all')
 const [showForm,setShowForm]=useState(false)
 const [type,setType]=useState<RequestType>('vacation')
 const [from,setFrom]=useState('2026-10-01');const [to,setTo]=useState('2026-10-01')
 const [details,setDetails]=useState('');const [recipient,setRecipient]=useState('')
 const [editing,setEditing]=useState<string|null>(null)
 const [feedback,setFeedback]=useState('');const [busy,setBusy]=useState(false)
 const [approval,setApproval]=useState<ShiftRequest|null>(null)
 const [resolutionId,setResolutionId]=useState<string|null>(null)
 const deciding=useRef(false)
 const [responses,setResponses]=useState<Record<string,string>>({})
 const authored=(r:ShiftRequest)=>r.created_by===profile.user_id||(!r.created_by&&!isSupervisor&&r.professional_id===profile.id)
 const received=(r:ShiftRequest)=>isSupervisor?!authored(r):!authored(r)||r.status!=='pending'
 const scoped=isSupervisor?requests:requests.filter(r=>r.professional_id===profile.id)
 const visible=scoped.filter(r=>(tab==='all'||(tab==='sent'?authored(r):received(r)))&&(statusFilter==='all'||r.status===statusFilter))
 useEffect(()=>{if(focusId){setTab('all');setStatusFilter('all');window.setTimeout(()=>document.getElementById(`request-${focusId}`)?.scrollIntoView({behavior:'smooth',block:'center'}),100)}},[focusId])
 useEffect(()=>{if(resolutionId)document.getElementById(`request-${resolutionId}`)?.scrollIntoView({behavior:'smooth',block:'start'})},[resolutionId])
 const seenIds=visible.filter(r=>unreadIds.includes(r.id)).map(r=>r.id)
 useEffect(()=>{if(!seenIds.length)return;const column=isSupervisor?'supervisor_seen_at':'professional_seen_at';const stamp=new Date().toISOString();if(demo){onChange(rows=>rows.map(r=>seenIds.includes(r.id)?{...r,[column]:stamp}:r));return}void supabase!.from('et_requests').update({[column]:stamp}).in('id',seenIds).then(({error})=>{if(!error)void reload()})},[seenIds.join('|'),isSupervisor])
 const reset=()=>{setEditing(null);setShowForm(false);setDetails('');setFeedback('')}
 const edit=(r:ShiftRequest)=>{setEditing(r.id);setType(r.request_type);setFrom(r.date_from);setTo(r.date_to);setDetails(r.details);setRecipient(r.professional_id);setShowForm(true);setFeedback('')}
 const submit=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setFeedback('');const content={request_type:type,date_from:from,date_to:to,details:details.trim()};if(demo){const stamp=new Date().toISOString();if(editing)onChange(rows=>rows.map(r=>r.id===editing?{...r,...content,supervisor_seen_at:null}:r));else onChange(rows=>[{...content,id:crypto.randomUUID(),professional_id:isSupervisor?recipient:profile.id,created_by:profile.user_id,status:'pending',created_at:stamp,supervisor_seen_at:isSupervisor?stamp:null,professional_seen_at:isSupervisor?null:stamp},...rows])}else{const {error}=editing?await supabase!.from('et_requests').update(content).eq('id',editing):await supabase!.from('et_requests').insert({...content,professional_id:isSupervisor?recipient:profile.id,status:'pending'});if(error){setFeedback(error.message);setBusy(false);return}await reload()}setBusy(false);reset();setTab('sent')}
 const decide=async(r:ShiftRequest,status:RequestStatus,confirmed=false)=>{
  if(busy||deciding.current)return
  if(status==='approved'&&isAbsenceRequest(r)&&!confirmed){setFeedback('');setApproval({...r});return}
  setBusy(true);deciding.current=true;setFeedback('')
  const content={status,supervisor_response:responses[r.id]??r.supervisor_response??''}
  try {
   if(demo)onChange(rows=>rows.map(x=>x.id===r.id?{...x,...content,professional_seen_at:null}:x))
   else {
    const {data,error}=await supabase!.from('et_requests').update(content).eq('id',r.id).eq('status',r.status).eq('professional_id',r.professional_id).eq('request_type',r.request_type).eq('date_from',r.date_from).eq('date_to',r.date_to).eq('details',r.details).select('id')
    if(error){setFeedback(error.message);return}
    if(!data?.length){setFeedback('La solicitud ha cambiado. Cierra esta revisión y actualiza los datos antes de decidir.');await reload();return}
    await reload()
   }
   setApproval(null)
   if(status==='approved'&&isAbsenceRequest(r)){setTab('all');setStatusFilter('all');setResolutionId(r.id);setFeedback('Ausencia aprobada. Revisa los turnos pendientes de cobertura y publica los meses afectados cuando termines.')}
  }catch{setFeedback('No se ha podido confirmar la respuesta. Actualiza los datos antes de volver a intentarlo.')}
  finally{setBusy(false);deciding.current=false}
 }
 const remove=async(r:ShiftRequest)=>{if(!window.confirm('¿seguro que quieres eliminar esto permanentemente?'))return;setBusy(true);if(demo)onChange(rows=>rows.filter(x=>x.id!==r.id));else{const {error}=await supabase!.from('et_requests').delete().eq('id',r.id);if(error)setFeedback(error.message);else await reload()}setBusy(false)}
 const sender=(r:ShiftRequest)=>staff.find(p=>p.user_id&&p.user_id===r.created_by)?.display_name??staff.find(p=>p.id===r.professional_id)?.display_name??'Profesional'
 const recipientName=(r:ShiftRequest)=>staff.find(p=>p.user_id===r.created_by)?.role==='supervisor'?staff.find(p=>p.id===r.professional_id)?.display_name:'Supervisión'
 return <section className="content-section"><div className="section-heading"><div><span className="eyebrow">Comunicación clara</span><h1>Solicitudes</h1><p>{isSupervisor?'Revisa las recibidas o consulta las que has enviado a profesionales.':'Envía solicitudes a supervisión y consulta las respuestas.'}</p></div><button className="primary" onClick={()=>{reset();setShowForm(true);setRecipient(staff.find(p=>p.active&&p.role==='professional')?.id??'')}}><Plus size={17}/> Nueva solicitud</button></div><div className="request-toolbar"><div className="segmented"><button className={tab==='received'?'active':''} onClick={()=>setTab('received')}>Recibidas ({scoped.filter(received).length})</button><button className={tab==='sent'?'active':''} onClick={()=>setTab('sent')}>Enviadas ({scoped.filter(authored).length})</button><button className={tab==='all'?'active':''} onClick={()=>setTab('all')}>Todas</button></div><label>Estado<select value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}><option value="all">Todos</option><option value="pending">Pendientes</option><option value="approved">Aprobadas</option><option value="rejected">Rechazadas</option></select></label></div>{!isSupervisor&&tab==='received'&&<p className="helper">Aquí aparecen las peticiones de supervisión y las respuestas a tus solicitudes.</p>}{feedback&&!showForm&&<p className="form-message" role="alert">{feedback}</p>}
 {unreadIds.some(id=>!visible.some(r=>r.id===id))&&<button className="unread-banner" onClick={()=>{setTab('all');setStatusFilter('all')}}><Bell size={17}/> Hay solicitudes nuevas fuera de este filtro. Ver nuevas</button>}<div className="requests-cards">{visible.map(r=><article id={`request-${r.id}`} key={r.id} className={`panel request-card ${focusId===r.id||resolutionId===r.id?'focused':''}`}><div className="request-card-heading"><span className={`status ${r.status}`}>{r.status==='pending'?'Pendiente':r.status==='approved'?'Aprobada':'Rechazada'}</span><small>Creada {format(parseISO(r.created_at),'d MMM · HH:mm',{locale:es})}</small></div><h2>{labels[r.request_type]}</h2><div className="request-route"><span><strong>De:</strong> {sender(r)}</span><span><strong>Para:</strong> {recipientName(r)}</span></div><p><strong>{format(parseISO(r.date_from),'d MMM',{locale:es})}{r.date_to!==r.date_from?` — ${format(parseISO(r.date_to),'d MMM',{locale:es})}`:''}</strong></p><p className="request-details">{r.details}</p>{isSupervisor&&<AbsenceImpact request={r} assignments={assignments} publishedAssignments={publishedAssignments} consultations={consultations} expanded={resolutionId===r.id} busy={busy} onReassign={onReassign} onCalendar={onCalendar}/>}{r.supervisor_response&&<p className="response-note"><strong>Respuesta:</strong> {r.supervisor_response}</p>}{isSupervisor&&<div className="request-decision"><label>Respuesta o motivo (opcional)<input maxLength={1000} value={responses[r.id]??r.supervisor_response??''} onChange={e=>setResponses({...responses,[r.id]:e.target.value})}/></label><div className="inline-actions"><button disabled={busy||r.status==='approved'} className="soft-button" onClick={()=>void decide(r,'approved')}><Check size={16}/> Aprobar</button><button disabled={busy} className="soft-button" onClick={()=>void decide(r,'rejected')}><X size={16}/> Rechazar</button>{r.status!=='pending'&&<button disabled={busy} className="text-button inline" onClick={()=>void decide(r,'pending')}>Volver a pendiente</button>}</div></div>}<div className="card-footer">{(isSupervisor||(r.created_by===profile.user_id&&r.status==='pending'))&&<button disabled={busy} className="soft-button" onClick={()=>edit(r)}><Pencil size={15}/> Editar</button>}<button disabled={busy} className="text-button inline danger-text" onClick={()=>void remove(r)}><Trash2 size={15}/> Eliminar</button></div></article>)}{!visible.length&&<div className="empty-state panel"><Bell/><p>No hay solicitudes en esta vista.</p></div>}</div>
 {approval&&<div className="modal-backdrop"><section className="modal wide-modal" role="dialog" aria-modal="true" aria-labelledby="absence-approval-title"><button className="modal-close" aria-label="Cerrar revisión de ausencia" disabled={busy} onClick={()=>{setApproval(null);setFeedback('')}}><X/></button><span className="eyebrow">Revisión antes de aprobar</span><h2 id="absence-approval-title">Aprobar {labels[approval.request_type].toLowerCase()}</h2><p><strong>{staff.find(p=>p.id===approval.professional_id)?.display_name}</strong> · {format(parseISO(approval.date_from),'dd/MM/yyyy')}–{format(parseISO(approval.date_to),'dd/MM/yyyy')}</p><p>{approval.details}</p><AbsenceImpact request={approval} assignments={assignments} publishedAssignments={publishedAssignments} consultations={consultations} expanded/><p className="helper">Aprobar la ausencia no reasigna ni publica turnos automáticamente.</p>{feedback&&<p role="alert" className="form-message">{feedback}</p>}<div className="modal-footer"><button className="soft-button" disabled={busy} onClick={()=>setApproval(null)}>Volver</button><button className="primary" disabled={busy} onClick={()=>void decide(approval,'approved',true)}>{busy?'Guardando…':'Confirmar aprobación'}</button></div></section></div>}
 {showForm&&<div className="modal-backdrop"><div className="modal" role="dialog" aria-modal="true" aria-label="Solicitud"><button className="modal-close" aria-label="Cerrar" onClick={reset}><X/></button><h2>{editing?'Editar solicitud':'Nueva solicitud'}</h2><form className="compact-form" onSubmit={submit}>{isSupervisor&&!editing?<label>Enviar a<select required value={recipient} onChange={e=>setRecipient(e.target.value)}>{staff.filter(p=>p.active&&p.role==='professional').map(p=><option key={p.id} value={p.id}>{p.display_name}</option>)}</select></label>:<p className="helper">{isSupervisor?'Profesional: '+staff.find(p=>p.id===recipient)?.display_name:'Destinataria: Supervisión'}</p>}<label>Tipo<select value={type} onChange={e=>setType(e.target.value as RequestType)}>{Object.entries(labels).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><div className="two-cols"><label>Desde<input required type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>Hasta<input required type="date" min={from} value={to} onChange={e=>setTo(e.target.value)}/></label></div><label>Detalle<textarea required minLength={3} maxLength={2000} value={details} onChange={e=>setDetails(e.target.value)}/></label>{feedback&&<p role="alert" className="form-message">{feedback}</p>}<button className="primary" disabled={busy}>{busy?'Guardando…':editing?'Guardar corrección':'Enviar solicitud'}</button></form></div></div>}
 </section>
}
