import { useEffect, useRef, useState } from 'react'
import { AlertTriangle, Check, Pencil, Plus, Trash2, X } from 'lucide-react'
import { format, parseISO } from 'date-fns'
import { es } from 'date-fns/locale'
import type { Assignment, CoverageProfile, Consultation, ShiftRequest, Staff } from '../types'
import { findCoverageCandidates } from '../lib/planning'
import { assignmentConflicts } from '../lib/scheduling'
export interface ShiftSelection { date:string; personId?:string; consultationId?:string; startTime?:string; endTime?:string }
export type AssignmentDraft = Omit<Assignment,'id'> & { id?: string }
export default function ShiftEditor({selection,staff,assignments,requests,consultations,editable,onClose,onSave,onRemove,coverageProfiles}:{selection:ShiftSelection;staff:Staff[];assignments:Assignment[];requests:ShiftRequest[];consultations:Consultation[];editable:boolean;coverageProfiles:CoverageProfile[];onClose:()=>void;onSave:(draft:AssignmentDraft)=>Promise<string|null>;onRemove:(a:Assignment)=>Promise<string|null>}) {
 const professionals=staff.filter(s=>s.active&&s.role==='professional')
 const initial=consultations.find(c=>c.id===(selection.consultationId??'PLANTA'))??consultations[0]
 const blank=():AssignmentDraft=>({professional_id:selection.personId??'',work_date:selection.date,consultation_id:initial?.id??'',start_time:selection.startTime??initial?.default_start_time?.slice(0,5)??'08:00',end_time:selection.endTime??initial?.default_end_time?.slice(0,5)??'15:00',notes:'',provisional:false,override_reason:''})
 const [draft,setDraft]=useState<AssignmentDraft>(blank)
 const [message,setMessage]=useState('')
 const [busy,setBusy]=useState(false)
 const [confirmed,setConfirmed]=useState(false)
 const [showCandidates,setShowCandidates]=useState(false)
 const heading=useRef<HTMLHeadingElement>(null)
 useEffect(()=>{heading.current?.focus();const key=(e:KeyboardEvent)=>{if(e.key==='Escape')onClose()};document.addEventListener('keydown',key);return()=>document.removeEventListener('keydown',key)},[])
 const conflicts=assignmentConflicts(draft,assignments,requests,consultations)
 const candidates=findCoverageCandidates(draft,staff,coverageProfiles,assignments,requests,consultations)
 const items=assignments.filter(a=>a.work_date===selection.date&&(!selection.personId||a.professional_id===selection.personId)&&(!selection.consultationId||a.consultation_id===selection.consultationId))
 const patch=(p:Partial<AssignmentDraft>)=>{setDraft(d=>({...d,...p}));setConfirmed(false);setMessage('')}
 const edit=(a:Assignment)=>{setDraft({...a,start_time:a.start_time.slice(0,5),end_time:a.end_time.slice(0,5),override_reason:''});setConfirmed(false);setMessage('')}
 const save=async(e:React.FormEvent)=>{e.preventDefault();if(draft.end_time<=draft.start_time){setMessage('La hora final debe ser posterior a la inicial.');return}if(conflicts.length&&(!confirmed||(draft.override_reason?.trim().length??0)<5)){setMessage('Revisa el conflicto y justifica la excepción antes de guardar.');return}setBusy(true);const error=await onSave({...draft,override_reason:conflicts.length?draft.override_reason:null});setBusy(false);if(error){setMessage(error);return}setDraft(blank());setConfirmed(false);setMessage('Turno guardado. El cuadrante y la cobertura se han actualizado.')}
 const remove=async(a:Assignment)=>{if(!window.confirm('¿Eliminar esta asignación? Podrás recuperarla desde Historial.'))return;setBusy(true);const error=await onRemove(a);setBusy(false);setMessage(error??'Asignación eliminada. Puedes recuperarla desde Historial.');if(!error&&draft.id===a.id)setDraft(blank())}
 return <div className="modal-backdrop"><div className="modal wide-modal" role="dialog" aria-modal="true" aria-label="Gestionar turnos"><button className="modal-close" aria-label="Cerrar panel" onClick={onClose}><X/></button><span className="eyebrow">{format(parseISO(selection.date),"EEEE d 'de' MMMM",{locale:es})}</span><h2 tabIndex={-1} ref={heading}>{selection.personId?staff.find(s=>s.id===selection.personId)?.display_name:consultations.find(c=>c.id===selection.consultationId)?.label??'Turnos del día'}</h2><div className="assignment-list">{items.map(a=><article key={a.id}><div><strong>{consultations.find(c=>c.id===a.consultation_id)?.label}</strong><small>{staff.find(s=>s.id===a.professional_id)?.display_name} · {a.start_time.slice(0,5)}–{a.end_time.slice(0,5)}</small>{a.notes&&<p>{a.notes}</p>}{a.override_reason&&<p className="exception-note">Excepción: {a.override_reason}</p>}</div>{editable&&<div className="inline-actions"><button className="soft-button" disabled={busy} onClick={()=>edit(a)}><Pencil size={15}/> Editar</button><button className="soft-button danger-text" disabled={busy} onClick={()=>void remove(a)}><Trash2 size={15}/> Eliminar</button></div>}</article>)}{!items.length&&<p className="helper">No hay asignaciones en esta selección.</p>}</div>
 {editable&&<form className="compact-form" onSubmit={save}><h3>{draft.id?'Editar asignación':'Asignar profesional'}</h3><div className="form-grid"><label>Profesional<select required value={draft.professional_id} onChange={e=>patch({professional_id:e.target.value})}><option value="">Selecciona una persona</option>{professionals.map(p=>{const busy=assignmentConflicts({...draft,professional_id:p.id},assignments,requests,consultations).length>0;return <option key={p.id} value={p.id}>{p.display_name}{busy?' · Revisar disponibilidad':''}</option>})}</select></label><label>Consulta<select value={draft.consultation_id} onChange={e=>{const c=consultations.find(c=>c.id===e.target.value)!;patch({consultation_id:c.id,start_time:c.default_start_time?.slice(0,5)??'08:00',end_time:c.default_end_time?.slice(0,5)??'15:00'})}}>{consultations.map(c=><option key={c.id} value={c.id}>{c.label}</option>)}</select></label><label>Día<input required type="date" min="2026-10-01" max="2026-12-31" value={draft.work_date} onChange={e=>patch({work_date:e.target.value})}/></label><label>Desde<input required type="time" value={draft.start_time} onChange={e=>patch({start_time:e.target.value})}/></label><label>Hasta<input required type="time" value={draft.end_time} onChange={e=>patch({end_time:e.target.value})}/></label></div><div className="candidate-picker"><button type="button" className="soft-button" onClick={()=>setShowCandidates(!showCandidates)}>{showCandidates?'Ocultar coberturas':'Buscar quién puede cubrir'}</button>{showCandidates&&<div><p className="helper">Según la consulta, fecha y horario de este formulario. Prioridad 1 es la primera consulta de la ficha personal.</p>{candidates.map(c=><article key={c.person.id}><div><strong>{c.person.display_name} · Prioridad {c.rank}</strong><small>{c.conflicts.length?c.conflicts.join(' '):'Sin solapamientos ni ausencias aprobadas'}</small></div><button className="soft-button" type="button" disabled={!!c.conflicts.length} onClick={()=>patch({professional_id:c.person.id})}>Seleccionar</button></article>)}{!candidates.length&&<p>Nadie tiene esta consulta en su ficha de cobertura.</p>}<p className="helper">{professionals.filter(p=>!coverageProfiles.some(c=>c.staff_id===p.id)).length} profesionales con ficha pendiente. No se incluyen en las sugerencias.</p></div>}</div><label>Notas opcionales<input maxLength={1000} value={draft.notes??''} onChange={e=>patch({notes:e.target.value})}/></label>
 {!!conflicts.length&&<div className="conflict-box" role="alert"><h3><AlertTriangle size={19}/> Revisa antes de guardar</h3>{conflicts.map((c,i)=><p key={i}>{c}</p>)}<label>Motivo de la excepción<textarea required minLength={5} maxLength={500} value={draft.override_reason??''} onChange={e=>setDraft({...draft,override_reason:e.target.value})} placeholder="Explica por qué se mantiene esta asignación…"/></label><label className="checkbox-label"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/> He revisado el conflicto y quiero mantener esta excepción.</label></div>}
 {message&&<p className="form-message" role="status">{message}</p>}<div className="modal-footer">{draft.id&&<button type="button" className="soft-button" onClick={()=>{setDraft(blank());setConfirmed(false);setMessage('')}}>Cancelar edición</button>}<button className="primary" disabled={busy||!draft.professional_id||Boolean(conflicts.length&&(!confirmed||(draft.override_reason?.trim().length??0)<5))}>{busy?'Guardando…':draft.id?<><Check size={17}/> Guardar cambios</>:<><Plus size={17}/> Añadir turno</>}</button></div></form>}
 </div></div>
}
