import {useEffect,useState} from 'react'
import {endOfMonth,format,parseISO} from 'date-fns'
import {X} from 'lucide-react'
import {supabase} from '../lib/supabase'
import {getPlanning} from '../lib/planningConfig'
import {buildCoverageIssues} from '../lib/coverage'
import {suggestMonth,type SuggestionContext,type SuggestedShift} from '../lib/suggestions'
export default function SuggestSchedule({month,context,demo,onClose,onSaved}:{month:string;context:SuggestionContext;demo:boolean;onClose:()=>void;onSaved:(rows:SuggestedShift[])=>Promise<void>}){
 const [snapshot,setSnapshot]=useState<SuggestionContext|null>(null),[result,setResult]=useState<ReturnType<typeof suggestMonth>|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[excluded,setExcluded]=useState<string[]>([]),[saved,setSaved]=useState(false)
 const generate=async()=>{setBusy(true);setMessage('');setResult(null);setSnapshot(null);setExcluded([]);try{let next=context;if(!demo){const {data,error}=await supabase!.rpc('et_suggestion_context');if(error)throw error;next=data as SuggestionContext}const generated=suggestMonth(month,next);setSnapshot(next);setResult(generated);setExcluded(generated.proposed.filter(a=>a.reference_exception).map(a=>a.id))}catch(e){setMessage(e instanceof Error?e.message:(e as {message?:string}).message??'No se ha podido preparar la propuesta.')}finally{setBusy(false)}}
 useEffect(()=>{void generate()},[])
 const rows=result?.proposed.filter(a=>!excluded.includes(a.id))??[]
 const issues=result&&snapshot?buildCoverageIssues([...snapshot.assignments,...rows],snapshot.consultations,snapshot.requests,month+'-01',format(endOfMonth(parseISO(month+'-01')),'yyyy-MM-dd'),snapshot.exceptions,snapshot.planning.holidays):[]
 const save=async()=>{if(!snapshot||!rows.length)return;setBusy(true);setMessage('');try{if(!demo){const {error}=await supabase!.rpc('et_apply_suggestion',{p_month:month+'-01',p_fingerprint:snapshot.fingerprint,p_rows:rows});if(error)throw error}await onSaved(rows);setSaved(true);setMessage(`${rows.length} turnos añadidos al borrador. Revisa el mes antes de publicarlo.`)}catch(e){setMessage((e as {message?:string}).message??'No se pudo guardar. Vuelve a generar la propuesta.')}finally{setBusy(false)}}
 const configChanged=snapshot&&snapshot.planning.updated_at!==getPlanning().updated_at
 return <div className="modal-backdrop"><div className="modal wide-modal" role="dialog" aria-modal="true" aria-label="Sugerir cuadrante"><button disabled={busy} className="modal-close" aria-label="Cerrar sugerencia" onClick={onClose}><X/></button><h2>Sugerir cuadrante · {month}</h2><p>Prioriza el profesional preferente y después los secundarios elegidos, según sus consultas y cadencias. Respeta ausencias aprobadas, festivos y jornada semanal. Conserva los turnos existentes.</p><p className="helper">Es una propuesta para revisar: puede dejar huecos y no garantiza la mejor combinación posible. Guardarla añade turnos provisionales al borrador; la publicación se hace después.</p>{busy&&!result&&<p role="status">Preparando propuesta…</p>}{result&&!saved&&<><strong>{rows.length} turnos propuestos · {issues.length} incidencias pendientes</strong>{result.warnings.length>0&&<details open><summary>Configuración que necesita revisión ({result.warnings.length})</summary><ul>{result.warnings.map(w=><li key={w}>{w}</li>)}</ul></details>}<div className="suggestion-list">{result.proposed.map(a=><label className="suggestion-row" key={a.id}><input type="checkbox" disabled={busy} checked={!excluded.includes(a.id)} onChange={e=>setExcluded(ids=>e.target.checked?ids.filter(id=>id!==a.id):[...ids,a.id])}/><span><strong>{a.work_date} · {snapshot?.consultations.find(c=>c.id===a.consultation_id)?.label}</strong><small>{a.start_time}–{a.end_time} · {snapshot?.staff.find(p=>p.id===a.professional_id)?.display_name} · {a.suggestion_reason}</small>{a.reference_exception&&<small className="review-text">No figura como habitual ni alternativa de esta regla. Se deja desmarcado por seguridad; márcalo solo si quieres aceptar esta cobertura excepcional.</small>}</span></label>)}</div>{!rows.length&&<p>No hay turnos nuevos para añadir. Revisa la configuración y los huecos pendientes.</p>}{result.proposed.some(a=>a.reference_exception)&&<p className="helper">Las coberturas excepcionales solo aparecen cuando no queda disponible ningún profesional habitual o alternativo compatible. Si no las marcas, el hueco seguirá pendiente para que puedas resolverlo manualmente.</p>}{issues.length>0&&<details><summary>Huecos e incidencias que seguirán pendientes</summary><ul>{issues.map(i=><li key={i.id}>{i.date} · {i.title} · {i.detail}</li>)}</ul></details>}</>}{configChanged&&<p className="form-message">Ha cambiado el periodo. Vuelve a generar la propuesta.</p>}{message&&<p className="form-message" role="status">{message}</p>}<div className="modal-footer"><button disabled={busy} className="soft-button" onClick={onClose}>{saved?'Cerrar':'Cancelar'}</button>{!saved&&<><button disabled={busy} className="soft-button" onClick={()=>void generate()}>Volver a sugerir</button><button className="primary" disabled={busy||!rows.length||!!configChanged} onClick={()=>void save()}>{busy?'Guardando…':'Añadir propuesta al borrador'}</button></>}</div></div></div>
}
