import { usePlanning, clampDate, periodLabel, planningMonths } from '../lib/planningConfig'
import { useState } from 'react'
import { AlertTriangle, ArrowRight, CalendarDays, CheckCircle2, Megaphone, Plus, Users } from 'lucide-react'
import { format, parseISO } from 'date-fns'
import { es } from 'date-fns/locale'
import type { Assignment, Consultation, ShiftRequest, Staff } from '../types'
import type { CoverageIssue } from '../lib/coverage'
import { assignmentConflicts, hasAbsence } from '../lib/scheduling'
import type { ShiftSelection } from './ShiftEditor'
export default function SupervisorHome({onException,staff,consultations,assignments,requests,issues,profile,onAssign,onCalendar,onRequest,onBroadcast,onTeam}:{onException?:(issue:CoverageIssue)=>void;staff:Staff[];consultations:Consultation[];assignments:Assignment[];requests:ShiftRequest[];issues:CoverageIssue[];profile:Staff;onAssign:(s:ShiftSelection)=>void;onCalendar:(date:string)=>void;onRequest:(id?:string)=>void;onBroadcast:()=>void;onTeam:()=>void}) {
 const planning=usePlanning(); const {start_date:ROTA_START,end_date:ROTA_END,holidays:HOLIDAYS}=planning
 const today=format(new Date(),'yyyy-MM-dd')
 const [date,setDate]=useState(today)
 const [scope,setScope]=useState('all')
 const [expanded,setExpanded]=useState(false)
 const pending=requests.filter(r=>r.status==='pending'&&r.created_by!==profile.user_id)
 const activeIssues=issues.filter(i=>i.date>=today&&(scope==='all'||i.date.startsWith(scope)))
 const professionals=staff.filter(s=>s.active&&s.role==='professional')
 const dayAssignments=assignments.filter(a=>a.work_date===date)
 const conflicts=assignments.filter(a=>a.work_date>=today&&assignmentConflicts(a,assignments,requests,consultations).length>0)
 const issueAction=(i:CoverageIssue)=>onAssign({date:i.date,consultationId:i.consultationId,startTime:i.startTime,endTime:i.endTime,findCoverage:i.kind==='shortage'})
 const queue = [
  ...activeIssues.map(i=>({id:`coverage-${i.id}`,date:i.date,level:i.severity==='critical'?0:1,title:i.title,detail:i.detail,action:i.kind==='suspended'?'Revisar turno':'Buscar cobertura',exceptionIssue:i.exceptionRule?i:undefined,run:()=>issueAction(i)})),
  ...conflicts.filter(a=>scope==='all'||a.work_date.startsWith(scope)).map(a=>({id:`conflict-${a.id}`,date:a.work_date,level:1,title:`Conflicto · ${staff.find(p=>p.id===a.professional_id)?.display_name??'Profesional'}`,detail:assignmentConflicts(a,assignments,requests,consultations).join(' '),action:'Revisar turno',exceptionIssue:undefined,run:()=>onAssign({date:a.work_date,personId:a.professional_id})})),
  ...pending.filter(r=>scope==='all'||r.date_from.startsWith(scope)).map(r=>({id:`request-${r.id}`,date:r.date_from,level:1,title:`Solicitud · ${staff.find(s=>s.user_id===r.created_by)?.display_name??staff.find(s=>s.id===r.professional_id)?.display_name??'Profesional'}`,detail:r.details,action:'Revisar solicitud',exceptionIssue:undefined,run:()=>onRequest(r.id)})),
 ].sort((a,b)=>a.level-b.level||a.date.localeCompare(b.date)||a.title.localeCompare(b.title))
 return <section className="content-section supervisor-home"><div className="section-heading"><div><span className="eyebrow">Tu centro de trabajo</span><h1>Mi equipo hoy</h1><p>Lo importante primero. Resuelve cada pendiente desde aquí.</p></div><button className="primary" onClick={()=>onCalendar(clampDate(date))}><CalendarDays size={18}/> Ver mes completo</button></div>
 <div className="home-metrics"><button onClick={()=>document.getElementById('coverage-priorities')?.scrollIntoView({behavior:'smooth'})}><span className="metric-icon critical"><AlertTriangle/></span><strong>{queue.filter(i=>i.level===0).length}</strong><span>Urgentes</span></button><button onClick={()=>document.getElementById('coverage-priorities')?.scrollIntoView({behavior:'smooth'})}><span className="metric-icon warning"><Users/></span><strong>{queue.filter(i=>i.level===1).length}</strong><span>Por revisar</span></button><button onClick={()=>onRequest()}><span className="metric-icon"><CalendarDays/></span><strong>{pending.length}</strong><span>Solicitudes pendientes</span></button></div>
 <div className="quick-actions"><button className="soft-button" onClick={()=>onAssign({date:clampDate(date)})}><Plus size={17}/> Asignar turno</button><button className="soft-button" onClick={onBroadcast}><Megaphone size={17}/> Escribir aviso</button><button className="soft-button" onClick={onTeam}><Users size={17}/> Equipo</button></div>
 <div className="dashboard-columns"><section className="panel priorities" id="coverage-priorities"><div className="section-heading"><div><h2>Pendientes de resolver <span className="queue-count">{queue.length}</span></h2><p>Cobertura, conflictos y solicitudes en una sola lista, ordenados por prioridad y fecha.</p></div><label className="scope-filter">Periodo<select value={scope} onChange={e=>{setScope(e.target.value);setExpanded(false)}}><option value="all">Todo el periodo</option>{planningMonths().map(m=><option key={m} value={m}>{format(parseISO(m+'-01'),'MMMM yyyy',{locale:es})}</option>)}</select></label></div>
 {queue.slice(0,expanded?queue.length:8).map(item=><article className={`priority-item ${item.level===0?'critical':'warning'}`} key={item.id}>{item.level===0?<AlertTriangle size={19}/>:<CalendarDays size={19}/>}<div><span className={`queue-level ${item.level===0?'urgent':'review'}`}>{item.level===0?'Urgente':'Revisar'}</span><strong>{item.title}</strong><small>{format(parseISO(item.date),'EEE d MMM',{locale:es})} · {item.detail}</small></div><button className="soft-button" onClick={item.run}>{item.action}<ArrowRight size={15}/></button>{item.exceptionIssue&&onException&&<button className="soft-button" onClick={()=>onException(item.exceptionIssue!)}>Añadir excepción</button>}</article>)}{queue.length>8&&<button className="text-button inline" onClick={()=>setExpanded(!expanded)}>{expanded?'Mostrar menos':`Ver los ${queue.length} pendientes`}</button>}
 {!queue.length&&<p className="all-clear"><CheckCircle2 size={18}/> No hay pendientes en este periodo.</p>}
 </section><section className="panel day-team"><div className="section-heading"><div><h2>{date===today?'Hoy en el equipo':'Equipo del día'}</h2><p>{format(parseISO(date),"EEEE d 'de' MMMM",{locale:es})}</p></div><label>Día<input type="date" required value={date} onChange={e=>e.target.value&&setDate(e.target.value)}/></label></div>{date<ROTA_START||date>ROTA_END?<p className="helper">El cuadrante disponible abarca {periodLabel()}. Elige un día de ese periodo para consultarlo.</p>:professionals.map(p=><article className="day-person" key={p.id}><strong>{p.display_name}</strong><div>{hasAbsence(p.id,date,requests)?<span className="absence-label">Ausencia aprobada</span>:null}{dayAssignments.filter(a=>a.professional_id===p.id).map(a=><span className="day-shift" key={a.id}><i style={{background:consultations.find(c=>c.id===a.consultation_id)?.color}}/>{consultations.find(c=>c.id===a.consultation_id)?.short_label} · {a.start_time.slice(0,5)}–{a.end_time.slice(0,5)}</span>)}{!dayAssignments.some(a=>a.professional_id===p.id)&&<small>Sin turno asignado</small>}</div><button className="text-button inline" onClick={()=>onAssign({date,personId:p.id})}>Gestionar</button></article>)}</section></div>
 </section>
}
