import { useState } from 'react'
import { AlertTriangle, ArrowRight, CalendarDays, CheckCircle2, Megaphone, Plus, Users } from 'lucide-react'
import { format, parseISO } from 'date-fns'
import { es } from 'date-fns/locale'
import type { Assignment, Consultation, ShiftRequest, Staff } from '../types'
import type { CoverageIssue } from '../lib/coverage'
import { assignmentConflicts, hasAbsence } from '../lib/scheduling'
import type { ShiftSelection } from './ShiftEditor'
export default function SupervisorHome({staff,consultations,assignments,requests,issues,profile,onAssign,onCalendar,onRequest,onBroadcast,onTeam}:{staff:Staff[];consultations:Consultation[];assignments:Assignment[];requests:ShiftRequest[];issues:CoverageIssue[];profile:Staff;onAssign:(s:ShiftSelection)=>void;onCalendar:(date:string)=>void;onRequest:(id?:string)=>void;onBroadcast:()=>void;onTeam:()=>void}) {
 const today=format(new Date(),'yyyy-MM-dd')
 const [date,setDate]=useState(today)
 const [scope,setScope]=useState('all')
 const [expanded,setExpanded]=useState(false)
 const pending=requests.filter(r=>r.status==='pending'&&r.created_by!==profile.user_id)
 const activeIssues=issues.filter(i=>i.date>=today&&(scope==='all'||i.date.startsWith(scope)))
 const professionals=staff.filter(s=>s.active&&s.role==='professional')
 const dayAssignments=assignments.filter(a=>a.work_date===date)
 const conflicts=assignments.filter(a=>a.work_date>=today&&assignmentConflicts(a,assignments,requests,consultations).length>0)
 const issueAction=(i:CoverageIssue)=>onAssign({date:i.date,consultationId:i.consultationId,startTime:i.startTime,endTime:i.endTime})
 return <section className="content-section supervisor-home"><div className="section-heading"><div><span className="eyebrow">Tu centro de trabajo</span><h1>Mi equipo hoy</h1><p>Lo importante primero. Resuelve cada pendiente desde aquí.</p></div><button className="primary" onClick={()=>onCalendar(date<'2026-10-01'?'2026-10-01':date>'2026-12-31'?'2026-12-01':date)}><CalendarDays size={18}/> Ver mes completo</button></div>
 <div className="home-metrics"><button onClick={()=>document.getElementById('coverage-priorities')?.scrollIntoView({behavior:'smooth'})}><span className="metric-icon critical"><AlertTriangle/></span><strong>{activeIssues.filter(i=>i.severity==='critical').length}</strong><span>Consultas sin cobertura suficiente</span></button><button onClick={()=>document.getElementById('coverage-priorities')?.scrollIntoView({behavior:'smooth'})}><span className="metric-icon warning"><Users/></span><strong>{activeIssues.filter(i=>i.severity==='warning').length}</strong><span>Cobertura por revisar</span></button><button onClick={()=>onRequest()}><span className="metric-icon"><CalendarDays/></span><strong>{pending.length}</strong><span>Solicitudes recibidas pendientes</span></button></div>
 <div className="quick-actions"><button className="soft-button" onClick={()=>onAssign({date:date<'2026-10-01'?'2026-10-01':date})}><Plus size={17}/> Asignar turno</button><button className="soft-button" onClick={onBroadcast}><Megaphone size={17}/> Escribir aviso</button><button className="soft-button" onClick={onTeam}><Users size={17}/> Equipo y consultas</button></div>
 <div className="dashboard-columns"><section className="panel priorities" id="coverage-priorities"><div className="section-heading"><div><h2>Necesita tu atención</h2><p>Consultas vacías, cobertura insuficiente y solicitudes.</p></div><label className="scope-filter">Periodo<select value={scope} onChange={e=>{setScope(e.target.value);setExpanded(false)}}><option value="all">Todo el trimestre</option><option value="2026-10">Octubre</option><option value="2026-11">Noviembre</option><option value="2026-12">Diciembre</option></select></label></div>
 {activeIssues.slice(0,expanded?activeIssues.length:6).map(i=><article className={`priority-item ${i.severity}`} key={i.id}><AlertTriangle size={19}/><div><strong>{i.title}</strong><small>{format(parseISO(i.date),'EEE d MMM',{locale:es})} · {i.detail}</small></div><button className="soft-button" onClick={()=>issueAction(i)}>{i.kind==='suspended'?'Revisar turno':'Asignar profesional'}<ArrowRight size={15}/></button></article>)}{activeIssues.length>6&&<button className="text-button inline" onClick={()=>setExpanded(!expanded)}>{expanded?'Mostrar menos':`Ver las ${activeIssues.length} incidencias`}</button>}
 {!activeIssues.length&&<p className="all-clear"><CheckCircle2 size={18}/> Cobertura completa según las reglas configuradas.</p>}
 {pending.slice(0,5).map(r=><article className="priority-item request-priority" key={r.id}><CalendarDays size={19}/><div><strong>Solicitud de {staff.find(s=>s.user_id===r.created_by)?.display_name??staff.find(s=>s.id===r.professional_id)?.display_name}</strong><small>{format(parseISO(r.date_from),'d MMM',{locale:es})} · {r.details}</small></div><button className="soft-button" onClick={()=>onRequest(r.id)}>Revisar solicitud<ArrowRight size={15}/></button></article>)}
 </section><section className="panel day-team"><div className="section-heading"><div><h2>{date===today?'Hoy en el equipo':'Equipo del día'}</h2><p>{format(parseISO(date),"EEEE d 'de' MMMM",{locale:es})}</p></div><label>Día<input type="date" required value={date} onChange={e=>e.target.value&&setDate(e.target.value)}/></label></div>{date<'2026-10-01'||date>'2026-12-31'?<p className="helper">El cuadrante disponible abarca octubre–diciembre de 2026. Elige un día de ese periodo para consultarlo.</p>:professionals.map(p=><article className="day-person" key={p.id}><strong>{p.display_name}</strong><div>{hasAbsence(p.id,date,requests)?<span className="absence-label">Ausencia aprobada</span>:null}{dayAssignments.filter(a=>a.professional_id===p.id).map(a=><span className="day-shift" key={a.id}><i style={{background:consultations.find(c=>c.id===a.consultation_id)?.color}}/>{consultations.find(c=>c.id===a.consultation_id)?.short_label} · {a.start_time.slice(0,5)}–{a.end_time.slice(0,5)}</span>)}{!dayAssignments.some(a=>a.professional_id===p.id)&&<small>Sin turno asignado</small>}</div><button className="text-button inline" onClick={()=>onAssign({date,personId:p.id})}>Gestionar</button></article>)}</section></div>
 {!!conflicts.length&&<section className="panel"><h2>Conflictos y excepciones del cuadrante</h2><p>Incluye turnos coincidentes y asignaciones durante ausencias aprobadas. Las excepciones justificadas se mantienen visibles.</p><div className="conflict-summary">{conflicts.slice(0,8).map(a=><article className="priority-item warning" key={a.id}><AlertTriangle size={18}/><div><strong>{staff.find(p=>p.id===a.professional_id)?.display_name} · {format(parseISO(a.work_date),'d MMM',{locale:es})}</strong><small>{assignmentConflicts(a,assignments,requests,consultations).join(' ')}</small>{a.override_reason&&<small>Excepción: {a.override_reason}</small>}</div><button className="soft-button" onClick={()=>onAssign({date:a.work_date,personId:a.professional_id})}>Revisar</button></article>)}</div>{conflicts.length>8&&<p>Hay {conflicts.length} turnos con conflictos. Los restantes aparecerán al resolver los anteriores.</p>}</section>}
 </section>
}
