// @vitest-environment jsdom
import { afterEach, describe, expect, it, vi } from 'vitest'
import { act } from 'react'
import { createRoot, type Root } from 'react-dom/client'
import App from '../App'
vi.mock('../lib/supabase',()=>({supabase:null,isSupabaseConfigured:false}))
let root:Root
let host:HTMLDivElement
const button=(text:string)=>{const b=[...host.querySelectorAll('button')].find(e=>e.textContent?.trim()===text);if(!b)throw Error(`Button not found: ${text}`);return b}
const click=async(text:string)=>{await act(async()=>button(text).click())}
const choose=async(el:HTMLSelectElement,value:string)=>{await act(async()=>{el.value=value;el.dispatchEvent(new Event('change',{bubbles:true}))})}
const change=async(el:HTMLInputElement|HTMLTextAreaElement,value:string)=>{await act(async()=>{const proto=el.tagName==='TEXTAREA'?HTMLTextAreaElement.prototype:HTMLInputElement.prototype;Object.getOwnPropertyDescriptor(proto,'value')!.set!.call(el,value);el.dispatchEvent(new Event('input',{bubbles:true}))})}
const label=(text:string)=>{const l=[...host.querySelectorAll('label')].find(e=>e.firstChild?.textContent?.trim()===text);if(!l)throw Error(`Label not found ${text}`);return l.querySelector('input,textarea,select')!}
async function enter(){(globalThis as any).IS_REACT_ACT_ENVIRONMENT=true;window.scrollTo=vi.fn();Element.prototype.scrollIntoView=vi.fn();host=document.createElement('div');document.body.append(host);root=createRoot(host);await act(async()=>root.render(<App/>));await click('Ver demostración interactiva')}
afterEach(async()=>{if(root)await act(async()=>root.unmount());host?.remove();vi.restoreAllMocks()})
describe('workspace interactions',()=>{
 it('opens supervisor home, full calendar, tasks with focus, and history',async()=>{await enter();expect(host.textContent).toContain('Mi equipo hoy');await click('Ver mes completo');expect(host.querySelectorAll('.day-head')).toHaveLength(31);await click('Añadir tarea');expect(document.activeElement?.getAttribute('placeholder')).toBe('Escribe una tarea pendiente…');await click('Historial');expect(host.textContent).toContain('Historial del cuadrante');await click('Equipo y consultas');expect(host.querySelectorAll('.consultation-cards article')).toHaveLength(12)})
 it('edits consultation coverage without changing existing shifts',async()=>{await enter();await click('Equipo y consultas');await click('Editar');await change(label('Nombre') as HTMLInputElement,'Planta revisada');await change(label('Profesionales necesarios') as HTMLInputElement,'3');await act(async()=>host.querySelector('form')!.dispatchEvent(new Event('submit',{bubbles:true,cancelable:true})));expect(host.querySelector('[role="dialog"]')).toBeNull();expect(host.textContent).toContain('Planta revisada');await click('Inicio');expect(host.textContent).toContain('Planta revisada: cobertura insuficiente')})
 it('requires a reviewed exception for conflicting shifts and records undo',async()=>{await enter();await click('Asignar turno');await choose(label('Profesional') as HTMLSelectElement,'demo-0001');await choose(label('Consulta') as HTMLSelectElement,'HDD');const conflict=host.querySelector('.conflict-box');expect(conflict).not.toBeNull();expect(button('Añadir turno').disabled).toBe(true);await change(label('Motivo de la excepción') as HTMLTextAreaElement,'Cobertura revisada y excepcional');await act(async()=>host.querySelector<HTMLInputElement>('.checkbox-label input')!.click());expect(button('Añadir turno').disabled).toBe(false);await act(async()=>host.querySelector('form')!.dispatchEvent(new Event('submit',{bubbles:true,cancelable:true})));expect(host.textContent).toContain('Turno guardado.');await act(async()=>host.querySelector<HTMLButtonElement>('[aria-label="Cerrar panel"]')!.click());await click('Historial');expect(host.textContent).toContain('Turno añadido');vi.spyOn(window,'confirm').mockReturnValue(true);await click('Deshacer cambio');expect(host.textContent).toContain('Cambio deshecho.')})
 it('separates supervisor sent requests from the inbox',async()=>{await enter();await click('Solicitudes');await click('Nueva solicitud');await change(label('Detalle') as HTMLTextAreaElement,'Solicitud de prueba a una profesional');await act(async()=>host.querySelector('form')!.dispatchEvent(new Event('submit',{bubbles:true,cancelable:true})));expect(host.textContent).toContain('Enviadas (1)');expect(host.querySelectorAll('.request-card')).toHaveLength(1);expect(host.querySelector('.request-route')?.textContent).toContain('Para:');await click('Recibidas (0)');expect(host.querySelectorAll('.request-card')).toHaveLength(0)})
 it('saves and reorders a professional coverage profile from the team card',async()=>{await enter();await click('Equipo y consultas');await click('Ver ficha personal');await choose(label('Añadir consulta') as HTMLSelectElement,'EN1');await click('Añadir');await choose(label('Añadir consulta') as HTMLSelectElement,'NUTRICION');await click('Añadir');await choose(label('Añadir consulta') as HTMLSelectElement,'PLANTA');await click('Añadir');await act(async()=>host.querySelector<HTMLButtonElement>('[aria-label="Subir PLANTA"]')!.click());await click('Guardar orden de consultas');expect([...host.querySelectorAll('.preference-list li strong')].map(e=>e.textContent)).toEqual(['EN1','Planta','Nutrición']);expect(host.textContent).toContain('Lista de consultas guardada.')})
 it('opens the absence calendar and copy preview from the rota',async()=>{await enter();await click('Cuadrante');await click('Ver ausencias');expect(host.querySelectorAll('.absence-day')).toHaveLength(31);await click('Volver al cuadrante');await click('Copiar semana o selección');expect(host.querySelector('[aria-label="Copiar turnos"]')).not.toBeNull();expect(host.textContent).toContain('bloqueados');expect(host.textContent).toContain('confirma la cadencia')})

})
