import {describe,it,expect} from 'vitest'
import {suggestMonth,type SuggestionContext} from './suggestions'
import {DEFAULT_PLANNING} from './planningConfig'
import type {CoverageRule} from '../types'
const rule:CoverageRule={id:'r',weekdays:[1],start_time:'08:00',end_time:'15:00',min_staff:1,every_weeks:1,anchor_date:'2026-10-05',monthly:false,valid_from:'2026-10-01',valid_until:'2026-10-31',suspensions:[]}
function context():SuggestionContext{return {fingerprint:'test',planning:DEFAULT_PLANNING,staff:['a','b','c'].map(id=>({id,user_id:null,display_name:id,username:id,role:'professional',mascot_key:'apple',active:true,weekly_minutes:2100})),consultations:[{id:'X',label:'X',short_label:'X',color:'#123456',active:true,preferred_staff_id:'a',secondary_staff_ids:['b','c'],coverage_rules:[rule]}],profiles:['a','b','c'].map(staff_id=>({staff_id,consultation_ids:['X'],work_cadences:[{...rule,id:'available',weekdays:[1,2,3,4,5]}]})),assignments:[],requests:[],exceptions:[]}}
describe('monthly suggestions',()=>{
 it('uses the primary, skips holidays, and does not mutate the draft',()=>{const ctx=context();const out=suggestMonth('2026-10',ctx);expect(out.proposed.map(a=>[a.work_date,a.professional_id])).toEqual([['2026-10-05','a'],['2026-10-19','a'],['2026-10-26','a']]);expect(ctx.assignments).toEqual([]);expect(out.issues).toEqual([])})
 it('uses an available secondary when primary is absent or off cadence',()=>{const ctx=context();ctx.requests=[{id:'r',professional_id:'a',request_type:'vacation',status:'approved',date_from:'2026-10-05',date_to:'2026-10-05',created_at:'',details:''}];ctx.profiles[0].work_cadences![0].every_weeks=2;const out=suggestMonth('2026-10',ctx);expect(out.proposed.map(a=>a.professional_id)).toEqual(['b','a','b'])})
 it('preserves existing shifts, avoids overlaps and honours required staffing',()=>{const ctx=context();ctx.consultations[0].coverage_rules=[{...rule,min_staff:2}];ctx.assignments=[{id:'old',professional_id:'a',consultation_id:'OTHER',work_date:'2026-10-05',start_time:'08:00',end_time:'15:00',provisional:false}];const out=suggestMonth('2026-10',ctx);expect(out.proposed.filter(a=>a.work_date==='2026-10-05').map(a=>a.professional_id)).toEqual(['b','c']);expect(out.issues).toHaveLength(0);expect(ctx.assignments).toHaveLength(1)})
 it('requires configured references, eligibility and personal cadences',()=>{const ctx=context();ctx.profiles=[];expect(suggestMonth('2026-10',ctx).proposed).toHaveLength(0);ctx.consultations[0].preferred_staff_id=null;expect(suggestMonth('2026-10',ctx).warnings.join()).toContain('preferente')})
 it('respects fortnightly services and suspension periods',()=>{const ctx=context();ctx.consultations[0].coverage_rules=[{...rule,every_weeks:2,suspensions:[{from:'2026-10-19',to:'2026-10-19'}]}];expect(suggestMonth('2026-10',ctx).proposed.map(a=>a.work_date)).toEqual(['2026-10-05'])})
 it('places only one monthly session and preserves an existing one',()=>{const ctx=context();ctx.consultations[0].coverage_rules=[{...rule,monthly:true}];const out=suggestMonth('2026-10',ctx);expect(out.proposed).toHaveLength(1);ctx.assignments=out.proposed;expect(suggestMonth('2026-10',ctx).proposed).toHaveLength(0)})
 it('does not exceed weekly minutes including shifts outside the month',()=>{const ctx=context();ctx.consultations[0].coverage_rules=[{...rule,weekdays:[4]}];ctx.staff.forEach(s=>s.weekly_minutes=420);ctx.assignments=ctx.staff.map(p=>({id:p.id,professional_id:p.id,work_date:'2026-09-28',consultation_id:'OTHER',start_time:'08:00',end_time:'15:00',provisional:false}));expect(suggestMonth('2026-10',ctx).proposed.some(a=>a.work_date==='2026-10-01')).toBe(false)})
 it('uses secondary consultation priorities and never silently chooses an unlisted person',()=>{const ctx=context();ctx.profiles[0].work_cadences=[];ctx.profiles[1].consultation_ids=['OTHER','X'];expect(suggestMonth('2026-10',ctx).proposed[0].professional_id).toBe('c');ctx.consultations[0].secondary_staff_ids=[];expect(suggestMonth('2026-10',ctx).proposed).toHaveLength(0)})
 it('keeps accepted Planta exceptions at one professional',()=>{const ctx=context();const r={...rule,min_staff:2};ctx.consultations[0]={...ctx.consultations[0],id:'PLANTA',coverage_rules:[r]};ctx.profiles.forEach(p=>p.consultation_ids=['PLANTA']);ctx.exceptions=[{id:'ex',work_date:'2026-10-05',consultation_id:'PLANTA',rule_id:'r',rule_snapshot:r,reason:'Imposible cubrir',created_by:'',created_by_name:'',created_at:'',revoked_at:null}];const out=suggestMonth('2026-10',ctx);expect(out.proposed.filter(a=>a.work_date==='2026-10-05')).toHaveLength(1);expect(out.issues).toHaveLength(0)})
 it('gives a scarce service its candidate before a flexible service',()=>{const ctx=context();ctx.consultations.push({...ctx.consultations[0],id:'Y',label:'Y',secondary_staff_ids:[]});ctx.profiles.forEach(p=>p.consultation_ids.push('Y'));const out=suggestMonth('2026-10',ctx);expect(out.proposed.filter(a=>a.work_date==='2026-10-05').map(a=>[a.consultation_id,a.professional_id])).toEqual([['X','b'],['Y','a']])})
})
